[2025-03-30T11:12:22.090+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T13:30:00+00:00 [queued]>
[2025-03-30T11:12:22.095+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T13:30:00+00:00 [queued]>
[2025-03-30T11:12:22.095+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:12:22.103+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-05 13:30:00+00:00
[2025-03-30T11:12:22.106+0000] {standard_task_runner.py:60} INFO - Started process 1356 to run task
[2025-03-30T11:12:22.118+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-05T13:30:00+00:00', '--job-id', '653', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpo3ff__pq']
[2025-03-30T11:12:22.119+0000] {standard_task_runner.py:88} INFO - Job 653: Subtask create_table
[2025-03-30T11:12:22.129+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:12:22.150+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T13:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:12:22.197+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-05T13:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-05T13:30:00+00:00'
[2025-03-30T11:12:22.199+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:12:22.199+0000] {inout_data.py:124} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:12:22.199+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:12:22.199+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:12:22.202+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241005T133000, start_date=20250330T111222, end_date=20250330T111222
[2025-03-30T11:12:22.216+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:12:22.236+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:18:59.096+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T13:30:00+00:00 [queued]>
[2025-03-30T11:18:59.123+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T13:30:00+00:00 [queued]>
[2025-03-30T11:18:59.127+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:18:59.172+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-05 13:30:00+00:00
[2025-03-30T11:18:59.184+0000] {standard_task_runner.py:60} INFO - Started process 3207 to run task
[2025-03-30T11:18:59.193+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-05T13:30:00+00:00', '--job-id', '1578', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpvyd16bam']
[2025-03-30T11:18:59.197+0000] {standard_task_runner.py:88} INFO - Job 1578: Subtask create_table
[2025-03-30T11:18:59.237+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:18:59.351+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T13:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:18:59.497+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-05T13:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-05T13:30:00+00:00'
[2025-03-30T11:18:59.506+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:18:59.508+0000] {inout_data.py:117} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:18:59.510+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:18:59.511+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:18:59.533+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241005T133000, start_date=20250330T111859, end_date=20250330T111859
[2025-03-30T11:18:59.637+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:18:59.709+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:31:13.340+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T13:30:00+00:00 [queued]>
[2025-03-30T11:31:13.349+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T13:30:00+00:00 [queued]>
[2025-03-30T11:31:13.350+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:31:13.368+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-05 13:30:00+00:00
[2025-03-30T11:31:13.375+0000] {standard_task_runner.py:60} INFO - Started process 5135 to run task
[2025-03-30T11:31:13.385+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-05T13:30:00+00:00', '--job-id', '2542', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpn5hayytj']
[2025-03-30T11:31:13.390+0000] {standard_task_runner.py:88} INFO - Job 2542: Subtask create_table
[2025-03-30T11:31:13.410+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:31:13.468+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T13:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:31:13.560+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-05T13:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-05T13:30:00+00:00'
[2025-03-30T11:31:13.566+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:31:13.569+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:31:13.570+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:31:13.571+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:31:13.587+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241005T133000, start_date=20250330T113113, end_date=20250330T113113
[2025-03-30T11:31:13.614+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:31:13.649+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
