[2025-03-30T11:12:02.468+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T23:30:00+00:00 [queued]>
[2025-03-30T11:12:02.475+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T23:30:00+00:00 [queued]>
[2025-03-30T11:12:02.477+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:12:02.500+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-04 23:30:00+00:00
[2025-03-30T11:12:02.507+0000] {standard_task_runner.py:60} INFO - Started process 1244 to run task
[2025-03-30T11:12:02.511+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-04T23:30:00+00:00', '--job-id', '596', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpuwpw9i_2']
[2025-03-30T11:12:02.512+0000] {standard_task_runner.py:88} INFO - Job 596: Subtask create_table
[2025-03-30T11:12:02.526+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:12:02.575+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T23:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:12:02.657+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T23:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-04T23:30:00+00:00'
[2025-03-30T11:12:02.662+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:12:02.664+0000] {inout_data.py:124} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:12:02.665+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:12:02.666+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:12:02.676+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241004T233000, start_date=20250330T111202, end_date=20250330T111202
[2025-03-30T11:12:02.694+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:12:02.726+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:18:37.433+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T23:30:00+00:00 [queued]>
[2025-03-30T11:18:37.454+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T23:30:00+00:00 [queued]>
[2025-03-30T11:18:37.455+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:18:37.506+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-04 23:30:00+00:00
[2025-03-30T11:18:37.525+0000] {standard_task_runner.py:60} INFO - Started process 3099 to run task
[2025-03-30T11:18:37.612+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-04T23:30:00+00:00', '--job-id', '1523', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpcai6b3_2']
[2025-03-30T11:18:37.620+0000] {standard_task_runner.py:88} INFO - Job 1523: Subtask create_table
[2025-03-30T11:18:37.698+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:18:37.798+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T23:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:18:37.941+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T23:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-04T23:30:00+00:00'
[2025-03-30T11:18:37.963+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:18:37.965+0000] {inout_data.py:117} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:18:37.966+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:18:37.966+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:18:38.016+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241004T233000, start_date=20250330T111837, end_date=20250330T111838
[2025-03-30T11:18:38.102+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:18:38.153+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:30:52.970+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T23:30:00+00:00 [queued]>
[2025-03-30T11:30:52.981+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T23:30:00+00:00 [queued]>
[2025-03-30T11:30:52.982+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:30:52.996+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-04 23:30:00+00:00
[2025-03-30T11:30:53.001+0000] {standard_task_runner.py:60} INFO - Started process 5018 to run task
[2025-03-30T11:30:53.005+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-04T23:30:00+00:00', '--job-id', '2483', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpycd_rxi1']
[2025-03-30T11:30:53.007+0000] {standard_task_runner.py:88} INFO - Job 2483: Subtask create_table
[2025-03-30T11:30:53.019+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:30:53.061+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T23:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:30:53.131+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T23:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-04T23:30:00+00:00'
[2025-03-30T11:30:53.137+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:30:53.138+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:30:53.138+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:30:53.139+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:30:53.147+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241004T233000, start_date=20250330T113052, end_date=20250330T113053
[2025-03-30T11:30:53.189+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:30:53.219+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
