[2025-03-30T11:10:44.200+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T16:30:00+00:00 [queued]>
[2025-03-30T11:10:44.217+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T16:30:00+00:00 [queued]>
[2025-03-30T11:10:44.218+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:10:44.226+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-10-02 16:30:00+00:00
[2025-03-30T11:10:44.229+0000] {standard_task_runner.py:60} INFO - Started process 810 to run task
[2025-03-30T11:10:44.232+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-10-02T16:30:00+00:00', '--job-id', '380', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmp767rnn2e']
[2025-03-30T11:10:44.233+0000] {standard_task_runner.py:88} INFO - Job 380: Subtask ingest_dummy_data
[2025-03-30T11:10:44.240+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:10:44.260+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T16:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:10:44.297+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T16:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-02T16:30:00+00:00'
[2025-03-30T11:10:44.301+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:10:44.304+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:44-1247' for key 'PRIMARY'")
[2025-03-30T11:10:44.305+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:44-1247' for key 'PRIMARY'")
[2025-03-30T11:10:44.305+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:44-1247' for key 'PRIMARY'")
[2025-03-30T11:10:44.305+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:44-1247' for key 'PRIMARY'")
[2025-03-30T11:10:44.307+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:44-1247' for key 'PRIMARY'")
[2025-03-30T11:10:44.308+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:44-1247' for key 'PRIMARY'")
[2025-03-30T11:10:44.309+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:44-1247' for key 'PRIMARY'")
[2025-03-30T11:10:44.311+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:44-1247' for key 'PRIMARY'")
[2025-03-30T11:10:44.311+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:44-1247' for key 'PRIMARY'")
[2025-03-30T11:10:44.312+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:44-1247' for key 'PRIMARY'")
[2025-03-30T11:10:44.312+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:44-1247' for key 'PRIMARY'")
[2025-03-30T11:10:44.312+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:44-1247' for key 'PRIMARY'")
[2025-03-30T11:10:44.313+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:44-1247' for key 'PRIMARY'")
[2025-03-30T11:10:44.313+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:44-1247' for key 'PRIMARY'")
[2025-03-30T11:10:44.313+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:44-1247' for key 'PRIMARY'")
[2025-03-30T11:10:44.313+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:44-1247' for key 'PRIMARY'")
[2025-03-30T11:10:44.313+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:44-1247' for key 'PRIMARY'")
[2025-03-30T11:10:44.314+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:44-1247' for key 'PRIMARY'")
[2025-03-30T11:10:44.314+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:44-1247' for key 'PRIMARY'")
[2025-03-30T11:10:44.314+0000] {inout_data.py:159} INFO - Ingested 20 rows of dummy data.
[2025-03-30T11:10:44.314+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:10:44.314+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:10:44.321+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20241002T163000, start_date=20250330T111044, end_date=20250330T111044
[2025-03-30T11:10:44.375+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:10:44.385+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:17:23.534+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T16:30:00+00:00 [queued]>
[2025-03-30T11:17:23.615+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T16:30:00+00:00 [queued]>
[2025-03-30T11:17:23.618+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:17:23.717+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-10-02 16:30:00+00:00
[2025-03-30T11:17:23.738+0000] {standard_task_runner.py:60} INFO - Started process 2673 to run task
[2025-03-30T11:17:23.762+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-10-02T16:30:00+00:00', '--job-id', '1310', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpmfrbqgxp']
[2025-03-30T11:17:23.765+0000] {standard_task_runner.py:88} INFO - Job 1310: Subtask ingest_dummy_data
[2025-03-30T11:17:23.809+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:17:23.889+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T16:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:17:24.057+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T16:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-02T16:30:00+00:00'
[2025-03-30T11:17:24.071+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:17:24.076+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:17:24-5551' for key 'PRIMARY'")
[2025-03-30T11:17:24.078+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:17:24-5551' for key 'PRIMARY'")
[2025-03-30T11:17:24.080+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:17:24-5551' for key 'PRIMARY'")
[2025-03-30T11:17:24.082+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:17:24-5551' for key 'PRIMARY'")
[2025-03-30T11:17:24.085+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:17:24-5551' for key 'PRIMARY'")
[2025-03-30T11:17:24.087+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:17:24-5551' for key 'PRIMARY'")
[2025-03-30T11:17:24.089+0000] {inout_data.py:152} INFO - Ingested 7 rows of dummy data.
[2025-03-30T11:17:24.090+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:17:24.091+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:17:24.108+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20241002T163000, start_date=20250330T111723, end_date=20250330T111724
[2025-03-30T11:17:24.149+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:17:24.191+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:29:50.133+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T16:30:00+00:00 [queued]>
[2025-03-30T11:29:50.150+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T16:30:00+00:00 [queued]>
[2025-03-30T11:29:50.151+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:29:50.174+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-10-02 16:30:00+00:00
[2025-03-30T11:29:50.180+0000] {standard_task_runner.py:60} INFO - Started process 4593 to run task
[2025-03-30T11:29:50.187+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-10-02T16:30:00+00:00', '--job-id', '2271', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpjmag7nad']
[2025-03-30T11:29:50.189+0000] {standard_task_runner.py:88} INFO - Job 2271: Subtask ingest_dummy_data
[2025-03-30T11:29:50.207+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:29:50.250+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T16:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:29:50.328+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T16:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-02T16:30:00+00:00'
[2025-03-30T11:29:50.333+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:29:50.334+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:29:50.335+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:29:50.335+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:29:50.337+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:29:50.339+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:29:50.340+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:29:50.343+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:29:50.343+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:29:50.344+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:29:50.345+0000] {inout_data.py:87} INFO - Ingested 9 rows of dummy data for 2024-10-02 16:30:00+00:00.
[2025-03-30T11:29:50.346+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:29:50.348+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:29:50.370+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20241002T163000, start_date=20250330T112950, end_date=20250330T112950
[2025-03-30T11:29:50.406+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:29:50.428+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:34:44.781+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T16:30:00+00:00 [queued]>
[2025-03-30T11:34:44.797+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T16:30:00+00:00 [queued]>
[2025-03-30T11:34:44.800+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:34:44.845+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-10-02 16:30:00+00:00
[2025-03-30T11:34:44.886+0000] {standard_task_runner.py:60} INFO - Started process 6050 to run task
[2025-03-30T11:34:44.907+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-10-02T16:30:00+00:00', '--job-id', '2998', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmp1341j1q8']
[2025-03-30T11:34:44.912+0000] {standard_task_runner.py:88} INFO - Job 2998: Subtask ingest_dummy_data
[2025-03-30T11:34:44.980+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:34:45.036+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T16:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:34:45.485+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T16:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-02T16:30:00+00:00'
[2025-03-30T11:34:45.513+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:34:45.517+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 34, 45, 517535), 'timestamp': datetime.datetime(2024, 10, 2, 16, 59, tzinfo=datetime.timezone.utc), 'emp_id': 2944, 'employee_name': 'Employee28', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '10', 'function': 'IT', 'division': 'AAPD', 'department': 'HRSD', 'section': '1'}
[2025-03-30T11:34:45.521+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:34:45.528+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 34, 45, 528385), 'timestamp': datetime.datetime(2024, 10, 2, 16, 47, tzinfo=datetime.timezone.utc), 'emp_id': 8834, 'employee_name': 'Employee16', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '6', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '1'}
[2025-03-30T11:34:45.533+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:34:45.535+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 34, 45, 535628), 'timestamp': datetime.datetime(2024, 10, 2, 16, 31, tzinfo=datetime.timezone.utc), 'emp_id': 8370, 'employee_name': 'Employee98', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '10', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '1'}
[2025-03-30T11:34:45.539+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:34:45.543+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 34, 45, 543385), 'timestamp': datetime.datetime(2024, 10, 2, 16, 34, tzinfo=datetime.timezone.utc), 'emp_id': 3561, 'employee_name': 'Employee74', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '1', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '1'}
[2025-03-30T11:34:45.545+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:34:45.553+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 34, 45, 553059), 'timestamp': datetime.datetime(2024, 10, 2, 16, 59, tzinfo=datetime.timezone.utc), 'emp_id': 4600, 'employee_name': 'Employee53', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '1', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '2'}
[2025-03-30T11:34:45.559+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:34:45.559+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 34, 45, 559939), 'timestamp': datetime.datetime(2024, 10, 2, 16, 54, tzinfo=datetime.timezone.utc), 'emp_id': 9595, 'employee_name': 'Employee28', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '6', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '2'}
[2025-03-30T11:34:45.564+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:34:45.568+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 34, 45, 568614), 'timestamp': datetime.datetime(2024, 10, 2, 16, 48, tzinfo=datetime.timezone.utc), 'emp_id': 9665, 'employee_name': 'Employee1', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '1', 'function': 'IT', 'division': 'BSID', 'department': 'HRSD', 'section': '1'}
[2025-03-30T11:34:45.574+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:34:45.574+0000] {inout_data.py:88} INFO - Ingested 7 rows of dummy data for 2024-10-02 16:30:00+00:00.
[2025-03-30T11:34:45.574+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:34:45.575+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:34:45.617+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20241002T163000, start_date=20250330T113444, end_date=20250330T113445
[2025-03-30T11:34:45.712+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:34:45.822+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
