[2025-03-30T11:13:10.598+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2025-03-30T11:13:10.618+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2025-03-30T11:13:10.622+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:13:10.646+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-07 00:00:00+00:00
[2025-03-30T11:13:10.653+0000] {standard_task_runner.py:60} INFO - Started process 1634 to run task
[2025-03-30T11:13:10.662+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-07T00:00:00+00:00', '--job-id', '791', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpn4wuvf3i']
[2025-03-30T11:13:10.666+0000] {standard_task_runner.py:88} INFO - Job 791: Subtask create_table
[2025-03-30T11:13:10.691+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:13:10.761+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-07T00:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:13:10.858+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-07T00:00:00+00:00'
[2025-03-30T11:13:10.867+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:13:10.870+0000] {inout_data.py:124} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:13:10.871+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:13:10.871+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:13:10.879+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241007T000000, start_date=20250330T111310, end_date=20250330T111310
[2025-03-30T11:13:10.924+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:13:10.939+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:19:52.344+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2025-03-30T11:19:52.360+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2025-03-30T11:19:52.361+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:19:52.391+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-07 00:00:00+00:00
[2025-03-30T11:19:52.396+0000] {standard_task_runner.py:60} INFO - Started process 3485 to run task
[2025-03-30T11:19:52.403+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-07T00:00:00+00:00', '--job-id', '1717', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmph6zdwkuw']
[2025-03-30T11:19:52.405+0000] {standard_task_runner.py:88} INFO - Job 1717: Subtask create_table
[2025-03-30T11:19:52.421+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:19:52.508+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-07T00:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:19:52.602+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-07T00:00:00+00:00'
[2025-03-30T11:19:52.614+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:19:52.615+0000] {inout_data.py:117} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:19:52.616+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:19:52.616+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:19:52.625+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241007T000000, start_date=20250330T111952, end_date=20250330T111952
[2025-03-30T11:19:52.669+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:19:52.698+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
