[2025-03-30T11:08:43.940+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-29T01:30:00+00:00 [queued]>
[2025-03-30T11:08:43.986+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-29T01:30:00+00:00 [queued]>
[2025-03-30T11:08:43.989+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:08:44.040+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-09-29 01:30:00+00:00
[2025-03-30T11:08:44.073+0000] {standard_task_runner.py:60} INFO - Started process 130 to run task
[2025-03-30T11:08:44.090+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-09-29T01:30:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpbbf6r1m7']
[2025-03-30T11:08:44.111+0000] {standard_task_runner.py:88} INFO - Job 38: Subtask ingest_dummy_data
[2025-03-30T11:08:44.196+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:08:44.458+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-29T01:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:08:45.330+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T01:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-29T01:30:00+00:00'
[2025-03-30T11:08:45.359+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:08:45.385+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:08:45-6263' for key 'PRIMARY'")
[2025-03-30T11:08:45.388+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:08:45-6263' for key 'PRIMARY'")
[2025-03-30T11:08:45.390+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:08:45-6263' for key 'PRIMARY'")
[2025-03-30T11:08:45.396+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:08:45-6263' for key 'PRIMARY'")
[2025-03-30T11:08:45.399+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:08:45-6263' for key 'PRIMARY'")
[2025-03-30T11:08:45.404+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:08:45-6263' for key 'PRIMARY'")
[2025-03-30T11:08:45.410+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:08:45-6263' for key 'PRIMARY'")
[2025-03-30T11:08:45.436+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:08:45-6263' for key 'PRIMARY'")
[2025-03-30T11:08:45.438+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:08:45-6263' for key 'PRIMARY'")
[2025-03-30T11:08:45.439+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:08:45-6263' for key 'PRIMARY'")
[2025-03-30T11:08:45.440+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:08:45-6263' for key 'PRIMARY'")
[2025-03-30T11:08:45.441+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:08:45-6263' for key 'PRIMARY'")
[2025-03-30T11:08:45.442+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:08:45-6263' for key 'PRIMARY'")
[2025-03-30T11:08:45.449+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:08:45-6263' for key 'PRIMARY'")
[2025-03-30T11:08:45.453+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:08:45-6263' for key 'PRIMARY'")
[2025-03-30T11:08:45.460+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:08:45-6263' for key 'PRIMARY'")
[2025-03-30T11:08:45.462+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:08:45-6263' for key 'PRIMARY'")
[2025-03-30T11:08:45.466+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:08:45-6263' for key 'PRIMARY'")
[2025-03-30T11:08:45.467+0000] {inout_data.py:159} INFO - Ingested 19 rows of dummy data.
[2025-03-30T11:08:45.469+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:08:45.472+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:08:45.608+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20240929T013000, start_date=20250330T110843, end_date=20250330T110845
[2025-03-30T11:08:45.856+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:08:46.066+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:15:26.590+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-29T01:30:00+00:00 [queued]>
[2025-03-30T11:15:26.619+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-29T01:30:00+00:00 [queued]>
[2025-03-30T11:15:26.621+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:15:26.660+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-09-29 01:30:00+00:00
[2025-03-30T11:15:26.669+0000] {standard_task_runner.py:60} INFO - Started process 1974 to run task
[2025-03-30T11:15:26.678+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-09-29T01:30:00+00:00', '--job-id', '961', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpfjtmrxxm']
[2025-03-30T11:15:26.680+0000] {standard_task_runner.py:88} INFO - Job 961: Subtask ingest_dummy_data
[2025-03-30T11:15:26.695+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:15:26.769+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-29T01:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:15:26.879+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T01:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-29T01:30:00+00:00'
[2025-03-30T11:15:26.890+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:15:26.900+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:15:26-3542' for key 'PRIMARY'")
[2025-03-30T11:15:26.901+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:15:26-3542' for key 'PRIMARY'")
[2025-03-30T11:15:26.903+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:15:26-3542' for key 'PRIMARY'")
[2025-03-30T11:15:26.905+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:15:26-3542' for key 'PRIMARY'")
[2025-03-30T11:15:26.906+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:15:26-3542' for key 'PRIMARY'")
[2025-03-30T11:15:26.907+0000] {inout_data.py:152} INFO - Ingested 6 rows of dummy data.
[2025-03-30T11:15:26.908+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:15:26.911+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:15:26.933+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20240929T013000, start_date=20250330T111526, end_date=20250330T111526
[2025-03-30T11:15:26.983+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:15:27.005+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:22:18.408+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-29T01:30:00+00:00 [queued]>
[2025-03-30T11:22:18.584+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-29T01:30:00+00:00 [queued]>
[2025-03-30T11:22:18.586+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:22:18.751+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-09-29 01:30:00+00:00
[2025-03-30T11:22:18.943+0000] {standard_task_runner.py:60} INFO - Started process 3838 to run task
[2025-03-30T11:22:18.972+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-09-29T01:30:00+00:00', '--job-id', '1891', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpmmu7qfop']
[2025-03-30T11:22:18.976+0000] {standard_task_runner.py:88} INFO - Job 1891: Subtask ingest_dummy_data
[2025-03-30T11:22:19.124+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:22:19.828+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-29T01:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:22:20.546+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T01:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-29T01:30:00+00:00'
[2025-03-30T11:22:20.572+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:22:20.580+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/inout_data.py", line 150, in ingest_dummy_data
    data = generate_dummy_data(logical_date)
  File "/opt/airflow/dags/inout_data.py", line 127, in generate_dummy_data
    timestamp = logical_date + timedelta(minutes=random.randint(0, 29)) #random minutes within the 30 minute interval
TypeError: can only concatenate str (not "datetime.timedelta") to str
[2025-03-30T11:22:20.760+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20240929T013000, start_date=20250330T112218, end_date=20250330T112220
[2025-03-30T11:22:20.904+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1891 for task ingest_dummy_data (can only concatenate str (not "datetime.timedelta") to str; 3838)
[2025-03-30T11:22:21.030+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-30T11:22:21.380+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:28:00.904+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-29T01:30:00+00:00 [queued]>
[2025-03-30T11:28:00.932+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-29T01:30:00+00:00 [queued]>
[2025-03-30T11:28:00.933+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:28:00.977+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-09-29 01:30:00+00:00
[2025-03-30T11:28:01.034+0000] {standard_task_runner.py:60} INFO - Started process 3893 to run task
[2025-03-30T11:28:01.050+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-09-29T01:30:00+00:00', '--job-id', '1920', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmp11zz3v0_']
[2025-03-30T11:28:01.058+0000] {standard_task_runner.py:88} INFO - Job 1920: Subtask ingest_dummy_data
[2025-03-30T11:28:01.128+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:28:01.271+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-29T01:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:28:01.579+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T01:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-29T01:30:00+00:00'
[2025-03-30T11:28:01.610+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:28:01.611+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:01.612+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:01.613+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:01.618+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:01.619+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:01.620+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:01.622+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:01.624+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:01.626+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:01.629+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:01.633+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:01.634+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:01.635+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:01.641+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:01.642+0000] {inout_data.py:87} INFO - Ingested 14 rows of dummy data for 2024-09-29 01:30:00+00:00.
[2025-03-30T11:28:01.648+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:28:01.652+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:28:01.685+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20240929T013000, start_date=20250330T112800, end_date=20250330T112801
[2025-03-30T11:28:01.763+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:28:01.902+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:32:41.830+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-29T01:30:00+00:00 [queued]>
[2025-03-30T11:32:41.878+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-29T01:30:00+00:00 [queued]>
[2025-03-30T11:32:41.882+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:32:41.960+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-09-29 01:30:00+00:00
[2025-03-30T11:32:41.965+0000] {standard_task_runner.py:60} INFO - Started process 5352 to run task
[2025-03-30T11:32:41.973+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-09-29T01:30:00+00:00', '--job-id', '2650', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpwr9y1hht']
[2025-03-30T11:32:41.980+0000] {standard_task_runner.py:88} INFO - Job 2650: Subtask ingest_dummy_data
[2025-03-30T11:32:42.055+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:32:42.293+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-29T01:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:32:42.439+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T01:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-29T01:30:00+00:00'
[2025-03-30T11:32:42.465+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:32:42.466+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 32, 42, 466145), 'timestamp': datetime.datetime(2024, 9, 29, 1, 54, tzinfo=datetime.timezone.utc), 'emp_id': 2988, 'employee_name': 'Employee74', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '3', 'function': 'IT', 'division': 'AAPD', 'department': 'ML', 'section': '2'}
[2025-03-30T11:32:42.471+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:32:42.472+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 32, 42, 472895), 'timestamp': datetime.datetime(2024, 9, 29, 1, 54, tzinfo=datetime.timezone.utc), 'emp_id': 5470, 'employee_name': 'Employee13', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '9', 'function': 'IT', 'division': 'AAPD', 'department': 'HRSD', 'section': '1'}
[2025-03-30T11:32:42.485+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:32:42.492+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 32, 42, 492390), 'timestamp': datetime.datetime(2024, 9, 29, 1, 47, tzinfo=datetime.timezone.utc), 'emp_id': 2256, 'employee_name': 'Employee20', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '6', 'function': 'IT', 'division': 'BSID', 'department': 'HRSD', 'section': '1'}
[2025-03-30T11:32:42.498+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:32:42.501+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 32, 42, 500890), 'timestamp': datetime.datetime(2024, 9, 29, 1, 38, tzinfo=datetime.timezone.utc), 'emp_id': 7835, 'employee_name': 'Employee97', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '9', 'function': 'IT', 'division': 'AAPD', 'department': 'HRSD', 'section': '1'}
[2025-03-30T11:32:42.513+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:32:42.520+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 32, 42, 520054), 'timestamp': datetime.datetime(2024, 9, 29, 1, 53, tzinfo=datetime.timezone.utc), 'emp_id': 9152, 'employee_name': 'Employee73', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '9', 'function': 'IT', 'division': 'AAPD', 'department': 'ML', 'section': '1'}
[2025-03-30T11:32:42.527+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:32:42.537+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 32, 42, 536836), 'timestamp': datetime.datetime(2024, 9, 29, 1, 48, tzinfo=datetime.timezone.utc), 'emp_id': 3954, 'employee_name': 'Employee42', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '3', 'function': 'IT', 'division': 'AAPD', 'department': 'ML', 'section': '2'}
[2025-03-30T11:32:42.540+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:32:42.544+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 32, 42, 544443), 'timestamp': datetime.datetime(2024, 9, 29, 1, 46, tzinfo=datetime.timezone.utc), 'emp_id': 2022, 'employee_name': 'Employee18', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '10', 'function': 'IT', 'division': 'BSID', 'department': 'HRSD', 'section': '1'}
[2025-03-30T11:32:42.550+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:32:42.577+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 32, 42, 577881), 'timestamp': datetime.datetime(2024, 9, 29, 1, 46, tzinfo=datetime.timezone.utc), 'emp_id': 8831, 'employee_name': 'Employee44', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '3', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '1'}
[2025-03-30T11:32:42.593+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:32:42.595+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 32, 42, 595610), 'timestamp': datetime.datetime(2024, 9, 29, 1, 35, tzinfo=datetime.timezone.utc), 'emp_id': 8133, 'employee_name': 'Employee32', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '8', 'function': 'IT', 'division': 'AAPD', 'department': 'ML', 'section': '1'}
[2025-03-30T11:32:42.596+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:32:42.596+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 32, 42, 596634), 'timestamp': datetime.datetime(2024, 9, 29, 1, 52, tzinfo=datetime.timezone.utc), 'emp_id': 3056, 'employee_name': 'Employee48', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '3', 'function': 'IT', 'division': 'BSID', 'department': 'HRSD', 'section': '1'}
[2025-03-30T11:32:42.598+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:32:42.599+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 32, 42, 599019), 'timestamp': datetime.datetime(2024, 9, 29, 1, 33, tzinfo=datetime.timezone.utc), 'emp_id': 8672, 'employee_name': 'Employee56', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '7', 'function': 'IT', 'division': 'AAPD', 'department': 'ML', 'section': '1'}
[2025-03-30T11:32:42.600+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:32:42.604+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 32, 42, 603573), 'timestamp': datetime.datetime(2024, 9, 29, 1, 32, tzinfo=datetime.timezone.utc), 'emp_id': 9141, 'employee_name': 'Employee82', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '6', 'function': 'IT', 'division': 'AAPD', 'department': 'ML', 'section': '2'}
[2025-03-30T11:32:42.609+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:32:42.612+0000] {inout_data.py:88} INFO - Ingested 12 rows of dummy data for 2024-09-29 01:30:00+00:00.
[2025-03-30T11:32:42.613+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:32:42.614+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:32:42.712+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20240929T013000, start_date=20250330T113241, end_date=20250330T113242
[2025-03-30T11:32:42.815+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:32:43.062+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:35:53.509+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-29T01:30:00+00:00 [queued]>
[2025-03-30T11:35:53.560+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-29T01:30:00+00:00 [queued]>
[2025-03-30T11:35:53.563+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:35:53.667+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-09-29 01:30:00+00:00
[2025-03-30T11:35:53.687+0000] {standard_task_runner.py:60} INFO - Started process 6194 to run task
[2025-03-30T11:35:53.702+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-09-29T01:30:00+00:00', '--job-id', '3070', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpa2wrig7o']
[2025-03-30T11:35:53.724+0000] {standard_task_runner.py:88} INFO - Job 3070: Subtask ingest_dummy_data
[2025-03-30T11:35:53.768+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:35:53.926+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-29T01:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:35:54.052+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T01:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-29T01:30:00+00:00'
[2025-03-30T11:35:54.063+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:35:54.073+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/inout_data.py", line 95, in ingest_dummy_data
    data = generate_dummy_data(logical_date) # pass logical_date string.
NameError: name 'generate_dummy_data' is not defined
[2025-03-30T11:35:54.096+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20240929T013000, start_date=20250330T113553, end_date=20250330T113554
[2025-03-30T11:35:54.120+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3070 for task ingest_dummy_data (name 'generate_dummy_data' is not defined; 6194)
[2025-03-30T11:35:54.150+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-30T11:35:54.218+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:38:05.336+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-29T01:30:00+00:00 [queued]>
[2025-03-30T11:38:05.378+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-29T01:30:00+00:00 [queued]>
[2025-03-30T11:38:05.383+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:38:05.438+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-09-29 01:30:00+00:00
[2025-03-30T11:38:05.520+0000] {standard_task_runner.py:60} INFO - Started process 6255 to run task
[2025-03-30T11:38:05.550+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-09-29T01:30:00+00:00', '--job-id', '3101', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmp03c88239']
[2025-03-30T11:38:05.564+0000] {standard_task_runner.py:88} INFO - Job 3101: Subtask ingest_dummy_data
[2025-03-30T11:38:05.712+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:38:05.999+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-29T01:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:38:06.414+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T01:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-29T01:30:00+00:00'
[2025-03-30T11:38:06.439+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:38:06.441+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 6, 441245), 'timestamp': datetime.datetime(2024, 9, 29, 1, 50, tzinfo=datetime.timezone.utc), 'emp_id': 8469, 'employee_name': 'Employee28', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '9', 'function': 'IT', 'division': 'AAPD', 'department': 'HRSD', 'section': '2'}
[2025-03-30T11:38:06.441+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:06.445+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 6, 445204), 'timestamp': datetime.datetime(2024, 9, 29, 1, 31, tzinfo=datetime.timezone.utc), 'emp_id': 6821, 'employee_name': 'Employee92', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '10', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '2'}
[2025-03-30T11:38:06.446+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:06.449+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 6, 449131), 'timestamp': datetime.datetime(2024, 9, 29, 1, 48, tzinfo=datetime.timezone.utc), 'emp_id': 8908, 'employee_name': 'Employee12', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '1', 'function': 'IT', 'division': 'AAPD', 'department': 'HRSD', 'section': '2'}
[2025-03-30T11:38:06.451+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:06.454+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 6, 454258), 'timestamp': datetime.datetime(2024, 9, 29, 1, 40, tzinfo=datetime.timezone.utc), 'emp_id': 2903, 'employee_name': 'Employee92', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '2', 'function': 'IT', 'division': 'BSID', 'department': 'HRSD', 'section': '1'}
[2025-03-30T11:38:06.457+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:06.461+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 6, 461010), 'timestamp': datetime.datetime(2024, 9, 29, 1, 55, tzinfo=datetime.timezone.utc), 'emp_id': 4345, 'employee_name': 'Employee66', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '1', 'function': 'IT', 'division': 'AAPD', 'department': 'ML', 'section': '1'}
[2025-03-30T11:38:06.463+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:06.466+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 6, 466772), 'timestamp': datetime.datetime(2024, 9, 29, 1, 43, tzinfo=datetime.timezone.utc), 'emp_id': 6491, 'employee_name': 'Employee43', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '9', 'function': 'IT', 'division': 'AAPD', 'department': 'HRSD', 'section': '1'}
[2025-03-30T11:38:06.469+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:06.471+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 6, 471152), 'timestamp': datetime.datetime(2024, 9, 29, 1, 32, tzinfo=datetime.timezone.utc), 'emp_id': 2502, 'employee_name': 'Employee25', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '7', 'function': 'IT', 'division': 'AAPD', 'department': 'CAPD', 'section': '2'}
[2025-03-30T11:38:06.473+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:06.476+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 6, 476706), 'timestamp': datetime.datetime(2024, 9, 29, 1, 30, tzinfo=datetime.timezone.utc), 'emp_id': 2994, 'employee_name': 'Employee57', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '5', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '2'}
[2025-03-30T11:38:06.479+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:06.486+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 6, 486238), 'timestamp': datetime.datetime(2024, 9, 29, 1, 54, tzinfo=datetime.timezone.utc), 'emp_id': 3916, 'employee_name': 'Employee42', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '9', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '1'}
[2025-03-30T11:38:06.492+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:06.496+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 6, 496536), 'timestamp': datetime.datetime(2024, 9, 29, 1, 55, tzinfo=datetime.timezone.utc), 'emp_id': 6090, 'employee_name': 'Employee88', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '8', 'function': 'IT', 'division': 'BSID', 'department': 'HRSD', 'section': '1'}
[2025-03-30T11:38:06.499+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:06.504+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 6, 504564), 'timestamp': datetime.datetime(2024, 9, 29, 1, 51, tzinfo=datetime.timezone.utc), 'emp_id': 1006, 'employee_name': 'Employee83', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '8', 'function': 'IT', 'division': 'AAPD', 'department': 'ML', 'section': '2'}
[2025-03-30T11:38:06.509+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:06.511+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 6, 511362), 'timestamp': datetime.datetime(2024, 9, 29, 1, 53, tzinfo=datetime.timezone.utc), 'emp_id': 3729, 'employee_name': 'Employee91', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '6', 'function': 'IT', 'division': 'BSID', 'department': 'HRSD', 'section': '1'}
[2025-03-30T11:38:06.518+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:06.522+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 6, 522042), 'timestamp': datetime.datetime(2024, 9, 29, 1, 56, tzinfo=datetime.timezone.utc), 'emp_id': 2108, 'employee_name': 'Employee98', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '1', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '2'}
[2025-03-30T11:38:06.523+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:06.531+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 6, 530961), 'timestamp': datetime.datetime(2024, 9, 29, 1, 35, tzinfo=datetime.timezone.utc), 'emp_id': 2649, 'employee_name': 'Employee98', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '9', 'function': 'IT', 'division': 'BSID', 'department': 'HRSD', 'section': '1'}
[2025-03-30T11:38:06.536+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:06.539+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 6, 538834), 'timestamp': datetime.datetime(2024, 9, 29, 1, 58, tzinfo=datetime.timezone.utc), 'emp_id': 9643, 'employee_name': 'Employee5', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '8', 'function': 'IT', 'division': 'AAPD', 'department': 'ML', 'section': '2'}
[2025-03-30T11:38:06.546+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:06.556+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 6, 555981), 'timestamp': datetime.datetime(2024, 9, 29, 1, 47, tzinfo=datetime.timezone.utc), 'emp_id': 2123, 'employee_name': 'Employee12', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '4', 'function': 'IT', 'division': 'BSID', 'department': 'HRSD', 'section': '2'}
[2025-03-30T11:38:06.559+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:06.567+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 6, 567231), 'timestamp': datetime.datetime(2024, 9, 29, 1, 47, tzinfo=datetime.timezone.utc), 'emp_id': 9923, 'employee_name': 'Employee57', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '2', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '2'}
[2025-03-30T11:38:06.569+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:06.571+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 6, 571465), 'timestamp': datetime.datetime(2024, 9, 29, 1, 47, tzinfo=datetime.timezone.utc), 'emp_id': 3791, 'employee_name': 'Employee21', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '3', 'function': 'IT', 'division': 'AAPD', 'department': 'HRSD', 'section': '2'}
[2025-03-30T11:38:06.574+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:06.583+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 6, 583186), 'timestamp': datetime.datetime(2024, 9, 29, 1, 37, tzinfo=datetime.timezone.utc), 'emp_id': 1029, 'employee_name': 'Employee54', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '2', 'function': 'IT', 'division': 'AAPD', 'department': 'ML', 'section': '1'}
[2025-03-30T11:38:06.585+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:06.587+0000] {inout_data.py:101} INFO - Ingested 19 rows of dummy data for 2024-09-29 01:30:00+00:00.
[2025-03-30T11:38:06.592+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:38:06.593+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:38:06.633+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20240929T013000, start_date=20250330T113805, end_date=20250330T113806
[2025-03-30T11:38:06.742+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:38:06.893+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:40:15.348+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-29T01:30:00+00:00 [queued]>
[2025-03-30T11:40:15.360+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-29T01:30:00+00:00 [queued]>
[2025-03-30T11:40:15.362+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:40:15.385+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-09-29 01:30:00+00:00
[2025-03-30T11:40:15.393+0000] {standard_task_runner.py:60} INFO - Started process 6696 to run task
[2025-03-30T11:40:15.401+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-09-29T01:30:00+00:00', '--job-id', '3322', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpxgjygeq1']
[2025-03-30T11:40:15.406+0000] {standard_task_runner.py:88} INFO - Job 3322: Subtask ingest_dummy_data
[2025-03-30T11:40:15.425+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:40:15.464+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-29T01:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:40:15.545+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T01:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-29T01:30:00+00:00'
[2025-03-30T11:40:15.556+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:40:15.557+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 15, 557095), 'timestamp': datetime.datetime(2024, 9, 29, 1, 45, tzinfo=datetime.timezone.utc), 'emp_id': 6795, 'employee_name': 'Employee83', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '2', 'function': 'IT', 'division': 'AAPD', 'department': 'HRSD', 'section': '2'}
[2025-03-30T11:40:15.557+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:15.557+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:15', '2024-09-29 01:45:00', 6795, 'Employee83', 'FactoryA', 'OUT', 'Side', '2', 'IT', 'AAPD', 'HRSD', '2')
[2025-03-30T11:40:15.557+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:15.558+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 15, 558014), 'timestamp': datetime.datetime(2024, 9, 29, 1, 37, tzinfo=datetime.timezone.utc), 'emp_id': 8829, 'employee_name': 'Employee3', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '8', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '2'}
[2025-03-30T11:40:15.558+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:15.558+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:15', '2024-09-29 01:37:00', 8829, 'Employee3', 'FactoryA', 'IN', 'Side', '8', 'IT', 'BSID', 'ML', '2')
[2025-03-30T11:40:15.558+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:15.559+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 15, 559009), 'timestamp': datetime.datetime(2024, 9, 29, 1, 48, tzinfo=datetime.timezone.utc), 'emp_id': 4581, 'employee_name': 'Employee25', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '6', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '2'}
[2025-03-30T11:40:15.559+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:15.559+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:15', '2024-09-29 01:48:00', 4581, 'Employee25', 'FactoryA', 'IN', 'Side', '6', 'IT', 'BSID', 'ML', '2')
[2025-03-30T11:40:15.559+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:15.559+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 15, 559757), 'timestamp': datetime.datetime(2024, 9, 29, 1, 55, tzinfo=datetime.timezone.utc), 'emp_id': 2537, 'employee_name': 'Employee18', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '5', 'function': 'IT', 'division': 'BSID', 'department': 'HRSD', 'section': '2'}
[2025-03-30T11:40:15.559+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:15.560+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:15', '2024-09-29 01:55:00', 2537, 'Employee18', 'FactoryA', 'OUT', 'Side', '5', 'IT', 'BSID', 'HRSD', '2')
[2025-03-30T11:40:15.560+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:15.562+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 15, 562305), 'timestamp': datetime.datetime(2024, 9, 29, 1, 42, tzinfo=datetime.timezone.utc), 'emp_id': 5720, 'employee_name': 'Employee97', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '4', 'function': 'IT', 'division': 'AAPD', 'department': 'CAPD', 'section': '2'}
[2025-03-30T11:40:15.562+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:15.562+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:15', '2024-09-29 01:42:00', 5720, 'Employee97', 'FactoryB', 'OUT', 'Side', '4', 'IT', 'AAPD', 'CAPD', '2')
[2025-03-30T11:40:15.563+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:15.563+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 15, 563364), 'timestamp': datetime.datetime(2024, 9, 29, 1, 50, tzinfo=datetime.timezone.utc), 'emp_id': 4407, 'employee_name': 'Employee68', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '9', 'function': 'IT', 'division': 'AAPD', 'department': 'CAPD', 'section': '2'}
[2025-03-30T11:40:15.563+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:15.563+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:15', '2024-09-29 01:50:00', 4407, 'Employee68', 'FactoryB', 'IN', 'Main', '9', 'IT', 'AAPD', 'CAPD', '2')
[2025-03-30T11:40:15.564+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:15.564+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 15, 564330), 'timestamp': datetime.datetime(2024, 9, 29, 1, 41, tzinfo=datetime.timezone.utc), 'emp_id': 8029, 'employee_name': 'Employee59', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '9', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '1'}
[2025-03-30T11:40:15.565+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:15.565+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:15', '2024-09-29 01:41:00', 8029, 'Employee59', 'FactoryA', 'OUT', 'Side', '9', 'IT', 'BSID', 'CAPD', '1')
[2025-03-30T11:40:15.565+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:15.568+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 15, 568638), 'timestamp': datetime.datetime(2024, 9, 29, 1, 48, tzinfo=datetime.timezone.utc), 'emp_id': 5385, 'employee_name': 'Employee21', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '1', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '2'}
[2025-03-30T11:40:15.573+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:15.573+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:15', '2024-09-29 01:48:00', 5385, 'Employee21', 'FactoryA', 'OUT', 'Side', '1', 'IT', 'BSID', 'ML', '2')
[2025-03-30T11:40:15.573+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:15.573+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 15, 573764), 'timestamp': datetime.datetime(2024, 9, 29, 1, 39, tzinfo=datetime.timezone.utc), 'emp_id': 2432, 'employee_name': 'Employee92', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '9', 'function': 'IT', 'division': 'BSID', 'department': 'HRSD', 'section': '2'}
[2025-03-30T11:40:15.575+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:15.577+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:15', '2024-09-29 01:39:00', 2432, 'Employee92', 'FactoryA', 'IN', 'Side', '9', 'IT', 'BSID', 'HRSD', '2')
[2025-03-30T11:40:15.577+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:15.577+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 15, 577823), 'timestamp': datetime.datetime(2024, 9, 29, 1, 34, tzinfo=datetime.timezone.utc), 'emp_id': 7435, 'employee_name': 'Employee29', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '8', 'function': 'IT', 'division': 'AAPD', 'department': 'CAPD', 'section': '2'}
[2025-03-30T11:40:15.578+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:15.578+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:15', '2024-09-29 01:34:00', 7435, 'Employee29', 'FactoryB', 'OUT', 'Main', '8', 'IT', 'AAPD', 'CAPD', '2')
[2025-03-30T11:40:15.578+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:15.582+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 15, 582122), 'timestamp': datetime.datetime(2024, 9, 29, 1, 52, tzinfo=datetime.timezone.utc), 'emp_id': 9191, 'employee_name': 'Employee49', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '5', 'function': 'IT', 'division': 'BSID', 'department': 'HRSD', 'section': '1'}
[2025-03-30T11:40:15.583+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:15.583+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:15', '2024-09-29 01:52:00', 9191, 'Employee49', 'FactoryA', 'OUT', 'Side', '5', 'IT', 'BSID', 'HRSD', '1')
[2025-03-30T11:40:15.585+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:15.587+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 15, 586951), 'timestamp': datetime.datetime(2024, 9, 29, 1, 59, tzinfo=datetime.timezone.utc), 'emp_id': 9404, 'employee_name': 'Employee14', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '3', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '2'}
[2025-03-30T11:40:15.587+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:15.588+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:15', '2024-09-29 01:59:00', 9404, 'Employee14', 'FactoryA', 'OUT', 'Main', '3', 'IT', 'BSID', 'CAPD', '2')
[2025-03-30T11:40:15.588+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:15.589+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 15, 589048), 'timestamp': datetime.datetime(2024, 9, 29, 1, 47, tzinfo=datetime.timezone.utc), 'emp_id': 2685, 'employee_name': 'Employee78', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '1', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '2'}
[2025-03-30T11:40:15.589+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:15.590+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:15', '2024-09-29 01:47:00', 2685, 'Employee78', 'FactoryA', 'IN', 'Main', '1', 'IT', 'BSID', 'ML', '2')
[2025-03-30T11:40:15.591+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:15.592+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 15, 592602), 'timestamp': datetime.datetime(2024, 9, 29, 1, 34, tzinfo=datetime.timezone.utc), 'emp_id': 5342, 'employee_name': 'Employee30', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '7', 'function': 'IT', 'division': 'AAPD', 'department': 'HRSD', 'section': '1'}
[2025-03-30T11:40:15.593+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:15.596+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:15', '2024-09-29 01:34:00', 5342, 'Employee30', 'FactoryA', 'OUT', 'Side', '7', 'IT', 'AAPD', 'HRSD', '1')
[2025-03-30T11:40:15.596+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:15.596+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 15, 596837), 'timestamp': datetime.datetime(2024, 9, 29, 1, 51, tzinfo=datetime.timezone.utc), 'emp_id': 3089, 'employee_name': 'Employee7', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '8', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '2'}
[2025-03-30T11:40:15.597+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:15.597+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:15', '2024-09-29 01:51:00', 3089, 'Employee7', 'FactoryA', 'IN', 'Side', '8', 'IT', 'BSID', 'ML', '2')
[2025-03-30T11:40:15.597+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:15.598+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 15, 598160), 'timestamp': datetime.datetime(2024, 9, 29, 1, 49, tzinfo=datetime.timezone.utc), 'emp_id': 8973, 'employee_name': 'Employee98', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '3', 'function': 'IT', 'division': 'AAPD', 'department': 'ML', 'section': '2'}
[2025-03-30T11:40:15.599+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:15.599+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:15', '2024-09-29 01:49:00', 8973, 'Employee98', 'FactoryB', 'OUT', 'Main', '3', 'IT', 'AAPD', 'ML', '2')
[2025-03-30T11:40:15.600+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:15.601+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 15, 601260), 'timestamp': datetime.datetime(2024, 9, 29, 1, 36, tzinfo=datetime.timezone.utc), 'emp_id': 8769, 'employee_name': 'Employee18', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '4', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '1'}
[2025-03-30T11:40:15.602+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:15.602+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:15', '2024-09-29 01:36:00', 8769, 'Employee18', 'FactoryB', 'OUT', 'Side', '4', 'IT', 'BSID', 'CAPD', '1')
[2025-03-30T11:40:15.603+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:15.604+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 15, 604293), 'timestamp': datetime.datetime(2024, 9, 29, 1, 46, tzinfo=datetime.timezone.utc), 'emp_id': 8379, 'employee_name': 'Employee33', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '4', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '2'}
[2025-03-30T11:40:15.605+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:15.607+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:15', '2024-09-29 01:46:00', 8379, 'Employee33', 'FactoryB', 'IN', 'Side', '4', 'IT', 'BSID', 'ML', '2')
[2025-03-30T11:40:15.609+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:15.610+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 15, 610467), 'timestamp': datetime.datetime(2024, 9, 29, 1, 37, tzinfo=datetime.timezone.utc), 'emp_id': 1849, 'employee_name': 'Employee56', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '2', 'function': 'IT', 'division': 'AAPD', 'department': 'CAPD', 'section': '2'}
[2025-03-30T11:40:15.610+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:15.611+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:15', '2024-09-29 01:37:00', 1849, 'Employee56', 'FactoryB', 'OUT', 'Side', '2', 'IT', 'AAPD', 'CAPD', '2')
[2025-03-30T11:40:15.611+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:15.611+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 15, 611434), 'timestamp': datetime.datetime(2024, 9, 29, 1, 48, tzinfo=datetime.timezone.utc), 'emp_id': 5699, 'employee_name': 'Employee43', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '8', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '1'}
[2025-03-30T11:40:15.611+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:15.612+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:15', '2024-09-29 01:48:00', 5699, 'Employee43', 'FactoryA', 'IN', 'Side', '8', 'IT', 'BSID', 'ML', '1')
[2025-03-30T11:40:15.612+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:15.614+0000] {inout_data.py:102} INFO - Ingested 20 rows of dummy data for 2024-09-29 01:30:00+00:00.
[2025-03-30T11:40:15.615+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:40:15.615+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:40:15.630+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20240929T013000, start_date=20250330T114015, end_date=20250330T114015
[2025-03-30T11:40:15.661+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:40:15.675+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
