[2025-03-30T11:12:10.400+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T03:30:00+00:00 [queued]>
[2025-03-30T11:12:10.436+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T03:30:00+00:00 [queued]>
[2025-03-30T11:12:10.437+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:12:10.481+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-05 03:30:00+00:00
[2025-03-30T11:12:10.536+0000] {standard_task_runner.py:60} INFO - Started process 1282 to run task
[2025-03-30T11:12:10.651+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-05T03:30:00+00:00', '--job-id', '615', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpm77awri7']
[2025-03-30T11:12:10.656+0000] {standard_task_runner.py:88} INFO - Job 615: Subtask create_table
[2025-03-30T11:12:10.724+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:12:10.824+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T03:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:12:10.960+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-05T03:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-05T03:30:00+00:00'
[2025-03-30T11:12:10.965+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:12:10.966+0000] {inout_data.py:124} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:12:10.967+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:12:10.968+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:12:10.979+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241005T033000, start_date=20250330T111210, end_date=20250330T111210
[2025-03-30T11:12:11.028+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:12:11.092+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:18:45.114+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T03:30:00+00:00 [queued]>
[2025-03-30T11:18:45.137+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T03:30:00+00:00 [queued]>
[2025-03-30T11:18:45.138+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:18:45.163+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-05 03:30:00+00:00
[2025-03-30T11:18:45.173+0000] {standard_task_runner.py:60} INFO - Started process 3126 to run task
[2025-03-30T11:18:45.188+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-05T03:30:00+00:00', '--job-id', '1537', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmps9adbk_0']
[2025-03-30T11:18:45.190+0000] {standard_task_runner.py:88} INFO - Job 1537: Subtask create_table
[2025-03-30T11:18:45.212+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:18:45.272+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T03:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:18:45.437+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-05T03:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-05T03:30:00+00:00'
[2025-03-30T11:18:45.456+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:18:45.462+0000] {inout_data.py:117} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:18:45.464+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:18:45.468+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:18:45.503+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241005T033000, start_date=20250330T111845, end_date=20250330T111845
[2025-03-30T11:18:45.582+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:18:45.655+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:30:57.472+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T03:30:00+00:00 [queued]>
[2025-03-30T11:30:57.498+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T03:30:00+00:00 [queued]>
[2025-03-30T11:30:57.499+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:30:57.535+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-05 03:30:00+00:00
[2025-03-30T11:30:57.562+0000] {standard_task_runner.py:60} INFO - Started process 5048 to run task
[2025-03-30T11:30:57.577+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-05T03:30:00+00:00', '--job-id', '2498', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpxlc37wfk']
[2025-03-30T11:30:57.582+0000] {standard_task_runner.py:88} INFO - Job 2498: Subtask create_table
[2025-03-30T11:30:57.596+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:30:57.642+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T03:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:30:57.796+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-05T03:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-05T03:30:00+00:00'
[2025-03-30T11:30:57.805+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:30:57.808+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:30:57.810+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:30:57.811+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:30:57.834+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241005T033000, start_date=20250330T113057, end_date=20250330T113057
[2025-03-30T11:30:57.916+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:30:57.975+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
