[2025-03-30T11:13:51.726+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-08T08:30:00+00:00 [queued]>
[2025-03-30T11:13:51.733+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-08T08:30:00+00:00 [queued]>
[2025-03-30T11:13:51.733+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:13:51.743+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-08 08:30:00+00:00
[2025-03-30T11:13:51.746+0000] {standard_task_runner.py:60} INFO - Started process 1894 to run task
[2025-03-30T11:13:51.751+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-08T08:30:00+00:00', '--job-id', '921', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmp1z65x__8']
[2025-03-30T11:13:51.752+0000] {standard_task_runner.py:88} INFO - Job 921: Subtask create_table
[2025-03-30T11:13:51.763+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:13:51.787+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-08T08:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:13:51.847+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T08:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-08T08:30:00+00:00'
[2025-03-30T11:13:51.851+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:13:51.852+0000] {inout_data.py:124} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:13:51.853+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:13:51.854+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:13:51.863+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241008T083000, start_date=20250330T111351, end_date=20250330T111351
[2025-03-30T11:13:51.888+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:13:51.907+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:20:38.279+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-08T08:30:00+00:00 [queued]>
[2025-03-30T11:20:38.298+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-08T08:30:00+00:00 [queued]>
[2025-03-30T11:20:38.300+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:20:38.351+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-08 08:30:00+00:00
[2025-03-30T11:20:38.362+0000] {standard_task_runner.py:60} INFO - Started process 3744 to run task
[2025-03-30T11:20:38.372+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-08T08:30:00+00:00', '--job-id', '1846', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpnvofkbim']
[2025-03-30T11:20:38.375+0000] {standard_task_runner.py:88} INFO - Job 1846: Subtask create_table
[2025-03-30T11:20:38.405+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:20:38.459+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-08T08:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:20:38.612+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T08:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-08T08:30:00+00:00'
[2025-03-30T11:20:38.624+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:20:38.625+0000] {inout_data.py:117} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:20:38.625+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:20:38.625+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:20:38.653+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241008T083000, start_date=20250330T112038, end_date=20250330T112038
[2025-03-30T11:20:38.714+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:20:38.749+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
