[2025-03-30T11:14:50.319+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-08T13:30:00+00:00 [queued]>
[2025-03-30T11:14:50.340+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-08T13:30:00+00:00 [queued]>
[2025-03-30T11:14:50.341+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:14:50.380+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-08 13:30:00+00:00
[2025-03-30T11:14:50.386+0000] {standard_task_runner.py:60} INFO - Started process 1927 to run task
[2025-03-30T11:14:50.394+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-08T13:30:00+00:00', '--job-id', '937', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpoootpurd']
[2025-03-30T11:14:50.395+0000] {standard_task_runner.py:88} INFO - Job 937: Subtask create_table
[2025-03-30T11:14:50.417+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:14:50.488+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-08T13:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:14:50.616+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T13:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-08T13:30:00+00:00'
[2025-03-30T11:14:50.626+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:14:50.629+0000] {inout_data.py:117} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:14:50.630+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:14:50.631+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:14:50.647+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241008T133000, start_date=20250330T111450, end_date=20250330T111450
[2025-03-30T11:14:50.740+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:14:50.801+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:20:45.463+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-08T13:30:00+00:00 [queued]>
[2025-03-30T11:20:45.470+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-08T13:30:00+00:00 [queued]>
[2025-03-30T11:20:45.471+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:20:45.481+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-08 13:30:00+00:00
[2025-03-30T11:20:45.487+0000] {standard_task_runner.py:60} INFO - Started process 3789 to run task
[2025-03-30T11:20:45.491+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-08T13:30:00+00:00', '--job-id', '1869', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpobdpxpae']
[2025-03-30T11:20:45.493+0000] {standard_task_runner.py:88} INFO - Job 1869: Subtask create_table
[2025-03-30T11:20:45.500+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:20:45.532+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-08T13:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:20:45.624+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T13:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-08T13:30:00+00:00'
[2025-03-30T11:20:45.630+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:20:45.631+0000] {inout_data.py:117} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:20:45.632+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:20:45.632+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:20:45.646+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241008T133000, start_date=20250330T112045, end_date=20250330T112045
[2025-03-30T11:20:45.671+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:20:45.711+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
