[2025-03-30T11:11:18.674+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-03T14:00:00+00:00 [queued]>
[2025-03-30T11:11:18.689+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-03T14:00:00+00:00 [queued]>
[2025-03-30T11:11:18.690+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:11:18.704+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-03 14:00:00+00:00
[2025-03-30T11:11:18.710+0000] {standard_task_runner.py:60} INFO - Started process 978 to run task
[2025-03-30T11:11:18.715+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-03T14:00:00+00:00', '--job-id', '463', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpt4k7kmjw']
[2025-03-30T11:11:18.716+0000] {standard_task_runner.py:88} INFO - Job 463: Subtask create_table
[2025-03-30T11:11:18.730+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:11:18.771+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-03T14:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:11:18.859+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-03T14:00:00+00:00'
[2025-03-30T11:11:18.863+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:11:18.864+0000] {inout_data.py:124} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:11:18.864+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:11:18.864+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:11:18.878+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241003T140000, start_date=20250330T111118, end_date=20250330T111118
[2025-03-30T11:11:18.897+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:11:18.919+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:17:48.490+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-03T14:00:00+00:00 [queued]>
[2025-03-30T11:17:48.503+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-03T14:00:00+00:00 [queued]>
[2025-03-30T11:17:48.503+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:17:48.517+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-03 14:00:00+00:00
[2025-03-30T11:17:48.520+0000] {standard_task_runner.py:60} INFO - Started process 2829 to run task
[2025-03-30T11:17:48.524+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-03T14:00:00+00:00', '--job-id', '1389', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpuzkqrier']
[2025-03-30T11:17:48.525+0000] {standard_task_runner.py:88} INFO - Job 1389: Subtask create_table
[2025-03-30T11:17:48.538+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:17:48.574+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-03T14:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:17:48.631+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-03T14:00:00+00:00'
[2025-03-30T11:17:48.633+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:17:48.634+0000] {inout_data.py:117} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:17:48.634+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:17:48.634+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:17:48.639+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241003T140000, start_date=20250330T111748, end_date=20250330T111748
[2025-03-30T11:17:48.665+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:17:48.678+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:30:14.178+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-03T14:00:00+00:00 [queued]>
[2025-03-30T11:30:14.190+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-03T14:00:00+00:00 [queued]>
[2025-03-30T11:30:14.191+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:30:14.222+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-03 14:00:00+00:00
[2025-03-30T11:30:14.226+0000] {standard_task_runner.py:60} INFO - Started process 4751 to run task
[2025-03-30T11:30:14.240+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-03T14:00:00+00:00', '--job-id', '2350', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmplxqz6rjc']
[2025-03-30T11:30:14.243+0000] {standard_task_runner.py:88} INFO - Job 2350: Subtask create_table
[2025-03-30T11:30:14.264+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:30:14.310+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-03T14:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:30:14.386+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-03T14:00:00+00:00'
[2025-03-30T11:30:14.400+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:30:14.404+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:30:14.405+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:30:14.407+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:30:14.416+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241003T140000, start_date=20250330T113014, end_date=20250330T113014
[2025-03-30T11:30:14.456+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:30:14.509+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
