[2025-03-30T11:11:49.751+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T14:30:00+00:00 [queued]>
[2025-03-30T11:11:49.773+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T14:30:00+00:00 [queued]>
[2025-03-30T11:11:49.776+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:11:49.830+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-04 14:30:00+00:00
[2025-03-30T11:11:49.847+0000] {standard_task_runner.py:60} INFO - Started process 1171 to run task
[2025-03-30T11:11:49.873+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-04T14:30:00+00:00', '--job-id', '559', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpbsj_256l']
[2025-03-30T11:11:49.880+0000] {standard_task_runner.py:88} INFO - Job 559: Subtask create_table
[2025-03-30T11:11:49.920+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:11:50.053+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T14:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:11:50.216+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T14:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-04T14:30:00+00:00'
[2025-03-30T11:11:50.226+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:11:50.227+0000] {inout_data.py:124} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:11:50.228+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:11:50.229+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:11:50.256+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241004T143000, start_date=20250330T111149, end_date=20250330T111150
[2025-03-30T11:11:50.357+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:11:50.947+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:18:23.073+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T14:30:00+00:00 [queued]>
[2025-03-30T11:18:23.101+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T14:30:00+00:00 [queued]>
[2025-03-30T11:18:23.102+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:18:23.126+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-04 14:30:00+00:00
[2025-03-30T11:18:23.196+0000] {standard_task_runner.py:60} INFO - Started process 3024 to run task
[2025-03-30T11:18:23.197+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-04T14:30:00+00:00', '--job-id', '1485', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmplvhbmjh1']
[2025-03-30T11:18:23.200+0000] {standard_task_runner.py:88} INFO - Job 1485: Subtask create_table
[2025-03-30T11:18:23.290+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:18:23.423+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T14:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:18:23.722+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T14:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-04T14:30:00+00:00'
[2025-03-30T11:18:23.775+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:18:23.792+0000] {inout_data.py:117} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:18:23.813+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:18:23.825+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:18:23.865+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241004T143000, start_date=20250330T111823, end_date=20250330T111823
[2025-03-30T11:18:23.976+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:18:24.176+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:30:42.816+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T14:30:00+00:00 [queued]>
[2025-03-30T11:30:42.826+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T14:30:00+00:00 [queued]>
[2025-03-30T11:30:42.827+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:30:42.850+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-04 14:30:00+00:00
[2025-03-30T11:30:42.856+0000] {standard_task_runner.py:60} INFO - Started process 4943 to run task
[2025-03-30T11:30:42.860+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-04T14:30:00+00:00', '--job-id', '2446', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpicf6rkbd']
[2025-03-30T11:30:42.863+0000] {standard_task_runner.py:88} INFO - Job 2446: Subtask create_table
[2025-03-30T11:30:42.877+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:30:42.930+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T14:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:30:43.020+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T14:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-04T14:30:00+00:00'
[2025-03-30T11:30:43.027+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:30:43.028+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:30:43.029+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:30:43.029+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:30:43.039+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241004T143000, start_date=20250330T113042, end_date=20250330T113043
[2025-03-30T11:30:43.086+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:30:43.153+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
