[2025-03-30T11:13:14.968+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-07T04:00:00+00:00 [queued]>
[2025-03-30T11:13:14.991+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-07T04:00:00+00:00 [queued]>
[2025-03-30T11:13:14.992+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:13:15.011+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-07 04:00:00+00:00
[2025-03-30T11:13:15.016+0000] {standard_task_runner.py:60} INFO - Started process 1665 to run task
[2025-03-30T11:13:15.040+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-07T04:00:00+00:00', '--job-id', '806', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpt5y810em']
[2025-03-30T11:13:15.048+0000] {standard_task_runner.py:88} INFO - Job 806: Subtask create_table
[2025-03-30T11:13:15.070+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:13:15.136+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-07T04:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:13:15.239+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-07T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-07T04:00:00+00:00'
[2025-03-30T11:13:15.246+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:13:15.248+0000] {inout_data.py:124} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:13:15.250+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:13:15.253+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:13:15.277+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241007T040000, start_date=20250330T111314, end_date=20250330T111315
[2025-03-30T11:13:15.325+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:13:15.373+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:19:57.322+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-07T04:00:00+00:00 [queued]>
[2025-03-30T11:19:57.332+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-07T04:00:00+00:00 [queued]>
[2025-03-30T11:19:57.333+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:19:57.350+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-07 04:00:00+00:00
[2025-03-30T11:19:57.354+0000] {standard_task_runner.py:60} INFO - Started process 3523 to run task
[2025-03-30T11:19:57.365+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-07T04:00:00+00:00', '--job-id', '1736', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpv57_h32e']
[2025-03-30T11:19:57.368+0000] {standard_task_runner.py:88} INFO - Job 1736: Subtask create_table
[2025-03-30T11:19:57.383+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:19:57.433+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-07T04:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:19:57.509+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-07T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-07T04:00:00+00:00'
[2025-03-30T11:19:57.515+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:19:57.517+0000] {inout_data.py:117} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:19:57.518+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:19:57.518+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:19:57.532+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241007T040000, start_date=20250330T111957, end_date=20250330T111957
[2025-03-30T11:19:57.586+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:19:57.602+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
