[2025-03-30T11:13:41.148+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-07T23:00:00+00:00 [queued]>
[2025-03-30T11:13:41.163+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-07T23:00:00+00:00 [queued]>
[2025-03-30T11:13:41.164+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:13:41.192+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-10-07 23:00:00+00:00
[2025-03-30T11:13:41.201+0000] {standard_task_runner.py:60} INFO - Started process 1831 to run task
[2025-03-30T11:13:41.221+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-10-07T23:00:00+00:00', '--job-id', '888', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpdnvzzra2']
[2025-03-30T11:13:41.226+0000] {standard_task_runner.py:88} INFO - Job 888: Subtask ingest_dummy_data
[2025-03-30T11:13:41.251+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:13:41.386+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-07T23:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:13:41.530+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-07T23:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-07T23:00:00+00:00'
[2025-03-30T11:13:41.539+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:13:41.542+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:13:41-3992' for key 'PRIMARY'")
[2025-03-30T11:13:41.544+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:13:41-3992' for key 'PRIMARY'")
[2025-03-30T11:13:41.546+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:13:41-3992' for key 'PRIMARY'")
[2025-03-30T11:13:41.547+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:13:41-3992' for key 'PRIMARY'")
[2025-03-30T11:13:41.549+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:13:41-3992' for key 'PRIMARY'")
[2025-03-30T11:13:41.551+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:13:41-3992' for key 'PRIMARY'")
[2025-03-30T11:13:41.553+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:13:41-3992' for key 'PRIMARY'")
[2025-03-30T11:13:41.555+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:13:41-3992' for key 'PRIMARY'")
[2025-03-30T11:13:41.556+0000] {inout_data.py:159} INFO - Ingested 9 rows of dummy data.
[2025-03-30T11:13:41.556+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:13:41.556+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:13:41.580+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20241007T230000, start_date=20250330T111341, end_date=20250330T111341
[2025-03-30T11:13:41.628+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:13:41.695+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:20:22.605+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-07T23:00:00+00:00 [queued]>
[2025-03-30T11:20:22.615+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-07T23:00:00+00:00 [queued]>
[2025-03-30T11:20:22.616+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:20:22.636+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-10-07 23:00:00+00:00
[2025-03-30T11:20:22.640+0000] {standard_task_runner.py:60} INFO - Started process 3677 to run task
[2025-03-30T11:20:22.644+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-10-07T23:00:00+00:00', '--job-id', '1814', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmprdtqsbzf']
[2025-03-30T11:20:22.645+0000] {standard_task_runner.py:88} INFO - Job 1814: Subtask ingest_dummy_data
[2025-03-30T11:20:22.655+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:20:22.729+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-07T23:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:20:22.855+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-07T23:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-07T23:00:00+00:00'
[2025-03-30T11:20:22.864+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:20:22.865+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:20:22-3603' for key 'PRIMARY'")
[2025-03-30T11:20:22.865+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:20:22-3603' for key 'PRIMARY'")
[2025-03-30T11:20:22.866+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:20:22-3603' for key 'PRIMARY'")
[2025-03-30T11:20:22.866+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:20:22-3603' for key 'PRIMARY'")
[2025-03-30T11:20:22.867+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:20:22-3603' for key 'PRIMARY'")
[2025-03-30T11:20:22.867+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:20:22-3603' for key 'PRIMARY'")
[2025-03-30T11:20:22.868+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:20:22-3603' for key 'PRIMARY'")
[2025-03-30T11:20:22.868+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:20:22-3603' for key 'PRIMARY'")
[2025-03-30T11:20:22.869+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:20:22-3603' for key 'PRIMARY'")
[2025-03-30T11:20:22.870+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:20:22-3603' for key 'PRIMARY'")
[2025-03-30T11:20:22.870+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:20:22-3603' for key 'PRIMARY'")
[2025-03-30T11:20:22.870+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:20:22-3603' for key 'PRIMARY'")
[2025-03-30T11:20:22.871+0000] {inout_data.py:152} INFO - Ingested 13 rows of dummy data.
[2025-03-30T11:20:22.871+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:20:22.871+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:20:22.877+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20241007T230000, start_date=20250330T112022, end_date=20250330T112022
[2025-03-30T11:20:22.907+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:20:22.919+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
