[2025-03-30T10:57:12.924+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dummy_data_ingestion.create_table manual__2025-03-30T10:57:11.499571+00:00 [queued]>
[2025-03-30T10:57:12.928+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dummy_data_ingestion.create_table manual__2025-03-30T10:57:11.499571+00:00 [queued]>
[2025-03-30T10:57:12.928+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T10:57:12.935+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2025-03-30 10:57:11.499571+00:00
[2025-03-30T10:57:12.939+0000] {standard_task_runner.py:60} INFO - Started process 88 to run task
[2025-03-30T10:57:12.946+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dummy_data_ingestion', 'create_table', 'manual__2025-03-30T10:57:11.499571+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpg1amtnvi']
[2025-03-30T10:57:12.950+0000] {standard_task_runner.py:88} INFO - Job 19: Subtask create_table
[2025-03-30T10:57:12.958+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T10:57:12.973+0000] {task_command.py:423} INFO - Running <TaskInstance: dummy_data_ingestion.create_table manual__2025-03-30T10:57:11.499571+00:00 [running]> on host ff9d64b065e6
[2025-03-30T10:57:13.004+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dummy_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T10:57:11.499571+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-30T10:57:11.499571+00:00'
[2025-03-30T10:57:13.006+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T10:57:13.006+0000] {inout_data.py:44} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T10:57:13.006+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T10:57:13.007+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T10:57:13.010+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=dummy_data_ingestion, task_id=create_table, execution_date=20250330T105711, start_date=20250330T105712, end_date=20250330T105713
[2025-03-30T10:57:13.042+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T10:57:13.054+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
