[2025-03-30T11:10:25.942+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-02T03:30:00+00:00 [queued]>
[2025-03-30T11:10:25.958+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-02T03:30:00+00:00 [queued]>
[2025-03-30T11:10:25.961+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:10:25.982+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-02 03:30:00+00:00
[2025-03-30T11:10:25.986+0000] {standard_task_runner.py:60} INFO - Started process 700 to run task
[2025-03-30T11:10:25.990+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-02T03:30:00+00:00', '--job-id', '324', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpbe3wopbx']
[2025-03-30T11:10:25.992+0000] {standard_task_runner.py:88} INFO - Job 324: Subtask create_table
[2025-03-30T11:10:26.008+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:10:26.072+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-02T03:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:10:26.164+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T03:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-02T03:30:00+00:00'
[2025-03-30T11:10:26.175+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:10:26.178+0000] {inout_data.py:124} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:10:26.179+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:10:26.179+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:10:26.187+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241002T033000, start_date=20250330T111025, end_date=20250330T111026
[2025-03-30T11:10:26.210+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:10:26.226+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:17:03.851+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-02T03:30:00+00:00 [queued]>
[2025-03-30T11:17:03.871+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-02T03:30:00+00:00 [queued]>
[2025-03-30T11:17:03.872+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:17:03.898+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-02 03:30:00+00:00
[2025-03-30T11:17:03.910+0000] {standard_task_runner.py:60} INFO - Started process 2554 to run task
[2025-03-30T11:17:03.915+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-02T03:30:00+00:00', '--job-id', '1251', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpxbiie71j']
[2025-03-30T11:17:03.919+0000] {standard_task_runner.py:88} INFO - Job 1251: Subtask create_table
[2025-03-30T11:17:03.940+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:17:03.981+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-02T03:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:17:04.055+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T03:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-02T03:30:00+00:00'
[2025-03-30T11:17:04.059+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:17:04.060+0000] {inout_data.py:117} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:17:04.061+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:17:04.061+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:17:04.069+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241002T033000, start_date=20250330T111703, end_date=20250330T111704
[2025-03-30T11:17:04.097+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:17:04.122+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:29:34.403+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-02T03:30:00+00:00 [queued]>
[2025-03-30T11:29:34.414+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-02T03:30:00+00:00 [queued]>
[2025-03-30T11:29:34.414+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:29:34.425+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-02 03:30:00+00:00
[2025-03-30T11:29:34.430+0000] {standard_task_runner.py:60} INFO - Started process 4475 to run task
[2025-03-30T11:29:34.437+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-02T03:30:00+00:00', '--job-id', '2212', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpfft589ub']
[2025-03-30T11:29:34.439+0000] {standard_task_runner.py:88} INFO - Job 2212: Subtask create_table
[2025-03-30T11:29:34.453+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:29:34.479+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-02T03:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:29:34.566+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T03:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-02T03:30:00+00:00'
[2025-03-30T11:29:34.572+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:29:34.575+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:29:34.575+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:29:34.575+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:29:34.588+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241002T033000, start_date=20250330T112934, end_date=20250330T112934
[2025-03-30T11:29:34.619+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:29:34.639+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:34:24.904+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-02T03:30:00+00:00 [queued]>
[2025-03-30T11:34:24.923+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-02T03:30:00+00:00 [queued]>
[2025-03-30T11:34:24.924+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:34:24.950+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-02 03:30:00+00:00
[2025-03-30T11:34:24.958+0000] {standard_task_runner.py:60} INFO - Started process 5931 to run task
[2025-03-30T11:34:24.974+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-02T03:30:00+00:00', '--job-id', '2940', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpwma2ahqo']
[2025-03-30T11:34:24.977+0000] {standard_task_runner.py:88} INFO - Job 2940: Subtask create_table
[2025-03-30T11:34:25.014+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:34:25.145+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-02T03:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:34:25.349+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T03:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-02T03:30:00+00:00'
[2025-03-30T11:34:25.376+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:34:25.379+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:34:25.380+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:34:25.382+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:34:25.408+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241002T033000, start_date=20250330T113424, end_date=20250330T113425
[2025-03-30T11:34:25.498+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:34:25.552+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:42:00.190+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-02T03:30:00+00:00 [queued]>
[2025-03-30T11:42:00.207+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-02T03:30:00+00:00 [queued]>
[2025-03-30T11:42:00.209+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:42:00.228+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-02 03:30:00+00:00
[2025-03-30T11:42:00.232+0000] {standard_task_runner.py:60} INFO - Started process 7272 to run task
[2025-03-30T11:42:00.237+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-02T03:30:00+00:00', '--job-id', '3611', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpvmbpdmqc']
[2025-03-30T11:42:00.240+0000] {standard_task_runner.py:88} INFO - Job 3611: Subtask create_table
[2025-03-30T11:42:00.249+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:42:00.294+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-02T03:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:42:00.345+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T03:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-02T03:30:00+00:00'
[2025-03-30T11:42:00.349+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:42:00.349+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:42:00.350+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:42:00.350+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:42:00.353+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241002T033000, start_date=20250330T114200, end_date=20250330T114200
[2025-03-30T11:42:00.377+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:42:00.389+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
