[2025-03-30T11:14:49.920+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-08T13:00:00+00:00 [queued]>
[2025-03-30T11:14:49.951+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-08T13:00:00+00:00 [queued]>
[2025-03-30T11:14:49.955+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:14:49.984+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-08 13:00:00+00:00
[2025-03-30T11:14:49.995+0000] {standard_task_runner.py:60} INFO - Started process 1922 to run task
[2025-03-30T11:14:49.999+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-08T13:00:00+00:00', '--job-id', '935', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpa3ln21an']
[2025-03-30T11:14:50.001+0000] {standard_task_runner.py:88} INFO - Job 935: Subtask create_table
[2025-03-30T11:14:50.029+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:14:50.120+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-08T13:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:14:50.284+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T13:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-08T13:00:00+00:00'
[2025-03-30T11:14:50.298+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:14:50.300+0000] {inout_data.py:117} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:14:50.302+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:14:50.303+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:14:50.330+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241008T130000, start_date=20250330T111449, end_date=20250330T111450
[2025-03-30T11:14:50.391+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:14:50.424+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:20:45.167+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-08T13:00:00+00:00 [queued]>
[2025-03-30T11:20:45.178+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-08T13:00:00+00:00 [queued]>
[2025-03-30T11:20:45.180+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:20:45.196+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-08 13:00:00+00:00
[2025-03-30T11:20:45.200+0000] {standard_task_runner.py:60} INFO - Started process 3780 to run task
[2025-03-30T11:20:45.207+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-08T13:00:00+00:00', '--job-id', '1866', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpxkmsqmm2']
[2025-03-30T11:20:45.210+0000] {standard_task_runner.py:88} INFO - Job 1866: Subtask create_table
[2025-03-30T11:20:45.223+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:20:45.255+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-08T13:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:20:45.338+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T13:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-08T13:00:00+00:00'
[2025-03-30T11:20:45.344+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:20:45.346+0000] {inout_data.py:117} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:20:45.346+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:20:45.347+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:20:45.359+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241008T130000, start_date=20250330T112045, end_date=20250330T112045
[2025-03-30T11:20:45.392+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:20:45.411+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
