[2025-03-30T11:12:32.916+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-05T19:00:00+00:00 [queued]>
[2025-03-30T11:12:32.946+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-05T19:00:00+00:00 [queued]>
[2025-03-30T11:12:32.948+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:12:32.986+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-10-05 19:00:00+00:00
[2025-03-30T11:12:33.000+0000] {standard_task_runner.py:60} INFO - Started process 1417 to run task
[2025-03-30T11:12:33.009+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-10-05T19:00:00+00:00', '--job-id', '682', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpl0vli5ta']
[2025-03-30T11:12:33.012+0000] {standard_task_runner.py:88} INFO - Job 682: Subtask ingest_dummy_data
[2025-03-30T11:12:33.035+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:12:33.077+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-05T19:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:12:33.188+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-05T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-05T19:00:00+00:00'
[2025-03-30T11:12:33.204+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:12:33.214+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:33-7259' for key 'PRIMARY'")
[2025-03-30T11:12:33.217+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:33-7259' for key 'PRIMARY'")
[2025-03-30T11:12:33.218+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:33-7259' for key 'PRIMARY'")
[2025-03-30T11:12:33.220+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:33-7259' for key 'PRIMARY'")
[2025-03-30T11:12:33.221+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:33-7259' for key 'PRIMARY'")
[2025-03-30T11:12:33.222+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:33-7259' for key 'PRIMARY'")
[2025-03-30T11:12:33.224+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:33-7259' for key 'PRIMARY'")
[2025-03-30T11:12:33.227+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:33-7259' for key 'PRIMARY'")
[2025-03-30T11:12:33.228+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:33-7259' for key 'PRIMARY'")
[2025-03-30T11:12:33.230+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:33-7259' for key 'PRIMARY'")
[2025-03-30T11:12:33.232+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:33-7259' for key 'PRIMARY'")
[2025-03-30T11:12:33.235+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:33-7259' for key 'PRIMARY'")
[2025-03-30T11:12:33.237+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:33-7259' for key 'PRIMARY'")
[2025-03-30T11:12:33.239+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:33-7259' for key 'PRIMARY'")
[2025-03-30T11:12:33.240+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:33-7259' for key 'PRIMARY'")
[2025-03-30T11:12:33.242+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:33-7259' for key 'PRIMARY'")
[2025-03-30T11:12:33.245+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:33-7259' for key 'PRIMARY'")
[2025-03-30T11:12:33.246+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:33-7259' for key 'PRIMARY'")
[2025-03-30T11:12:33.247+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:33-7259' for key 'PRIMARY'")
[2025-03-30T11:12:33.248+0000] {inout_data.py:159} INFO - Ingested 20 rows of dummy data.
[2025-03-30T11:12:33.249+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:12:33.250+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:12:33.266+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20241005T190000, start_date=20250330T111232, end_date=20250330T111233
[2025-03-30T11:12:33.314+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:12:33.359+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:19:10.816+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-05T19:00:00+00:00 [queued]>
[2025-03-30T11:19:10.841+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-05T19:00:00+00:00 [queued]>
[2025-03-30T11:19:10.842+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:19:10.868+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-10-05 19:00:00+00:00
[2025-03-30T11:19:10.884+0000] {standard_task_runner.py:60} INFO - Started process 3271 to run task
[2025-03-30T11:19:10.894+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-10-05T19:00:00+00:00', '--job-id', '1609', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmphn9r202g']
[2025-03-30T11:19:10.908+0000] {standard_task_runner.py:88} INFO - Job 1609: Subtask ingest_dummy_data
[2025-03-30T11:19:10.947+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:19:11.110+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-05T19:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:19:11.358+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-05T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-05T19:00:00+00:00'
[2025-03-30T11:19:11.380+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:19:11.388+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:19:11-5954' for key 'PRIMARY'")
[2025-03-30T11:19:11.392+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:19:11-5954' for key 'PRIMARY'")
[2025-03-30T11:19:11.394+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:19:11-5954' for key 'PRIMARY'")
[2025-03-30T11:19:11.396+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:19:11-5954' for key 'PRIMARY'")
[2025-03-30T11:19:11.397+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:19:11-5954' for key 'PRIMARY'")
[2025-03-30T11:19:11.399+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:19:11-5954' for key 'PRIMARY'")
[2025-03-30T11:19:11.401+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:19:11-5954' for key 'PRIMARY'")
[2025-03-30T11:19:11.403+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:19:11-5954' for key 'PRIMARY'")
[2025-03-30T11:19:11.405+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:19:11-5954' for key 'PRIMARY'")
[2025-03-30T11:19:11.408+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:19:11-5954' for key 'PRIMARY'")
[2025-03-30T11:19:11.411+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:19:11-5954' for key 'PRIMARY'")
[2025-03-30T11:19:11.416+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:19:11-5954' for key 'PRIMARY'")
[2025-03-30T11:19:11.417+0000] {inout_data.py:152} INFO - Ingested 13 rows of dummy data.
[2025-03-30T11:19:11.419+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:19:11.420+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:19:11.443+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20241005T190000, start_date=20250330T111910, end_date=20250330T111911
[2025-03-30T11:19:11.508+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:19:11.760+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:31:20.116+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-05T19:00:00+00:00 [queued]>
[2025-03-30T11:31:20.133+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-05T19:00:00+00:00 [queued]>
[2025-03-30T11:31:20.134+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:31:20.161+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-10-05 19:00:00+00:00
[2025-03-30T11:31:20.172+0000] {standard_task_runner.py:60} INFO - Started process 5189 to run task
[2025-03-30T11:31:20.176+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-10-05T19:00:00+00:00', '--job-id', '2568', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmphh6xtduh']
[2025-03-30T11:31:20.178+0000] {standard_task_runner.py:88} INFO - Job 2568: Subtask ingest_dummy_data
[2025-03-30T11:31:20.192+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:31:20.232+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-05T19:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:31:20.344+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-05T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-05T19:00:00+00:00'
[2025-03-30T11:31:20.349+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:31:20.351+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:31:20.351+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:31:20.352+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:31:20.353+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:31:20.354+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:31:20.355+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:31:20.355+0000] {inout_data.py:87} INFO - Ingested 6 rows of dummy data for 2024-10-05 19:00:00+00:00.
[2025-03-30T11:31:20.356+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:31:20.357+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:31:20.374+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20241005T190000, start_date=20250330T113120, end_date=20250330T113120
[2025-03-30T11:31:20.404+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:31:20.432+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
