[2025-03-30T11:10:24.362+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-02T00:30:00+00:00 [queued]>
[2025-03-30T11:10:24.372+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-02T00:30:00+00:00 [queued]>
[2025-03-30T11:10:24.372+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:10:24.390+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-02 00:30:00+00:00
[2025-03-30T11:10:24.397+0000] {standard_task_runner.py:60} INFO - Started process 678 to run task
[2025-03-30T11:10:24.408+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-02T00:30:00+00:00', '--job-id', '313', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpowcocnh9']
[2025-03-30T11:10:24.409+0000] {standard_task_runner.py:88} INFO - Job 313: Subtask create_table
[2025-03-30T11:10:24.439+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:10:24.483+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-02T00:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:10:24.573+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T00:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-02T00:30:00+00:00'
[2025-03-30T11:10:24.587+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:10:24.588+0000] {inout_data.py:124} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:10:24.588+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:10:24.589+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:10:24.610+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241002T003000, start_date=20250330T111024, end_date=20250330T111024
[2025-03-30T11:10:24.632+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:10:24.660+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:16:59.066+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-02T00:30:00+00:00 [queued]>
[2025-03-30T11:16:59.089+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-02T00:30:00+00:00 [queued]>
[2025-03-30T11:16:59.094+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:16:59.130+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-02 00:30:00+00:00
[2025-03-30T11:16:59.138+0000] {standard_task_runner.py:60} INFO - Started process 2531 to run task
[2025-03-30T11:16:59.148+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-02T00:30:00+00:00', '--job-id', '1239', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpj3pa1d5j']
[2025-03-30T11:16:59.149+0000] {standard_task_runner.py:88} INFO - Job 1239: Subtask create_table
[2025-03-30T11:16:59.171+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:16:59.206+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-02T00:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:16:59.336+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T00:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-02T00:30:00+00:00'
[2025-03-30T11:16:59.341+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:16:59.343+0000] {inout_data.py:117} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:16:59.344+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:16:59.344+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:16:59.360+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241002T003000, start_date=20250330T111659, end_date=20250330T111659
[2025-03-30T11:16:59.409+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:16:59.475+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:29:30.891+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-02T00:30:00+00:00 [queued]>
[2025-03-30T11:29:30.907+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-02T00:30:00+00:00 [queued]>
[2025-03-30T11:29:30.908+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:29:30.928+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-02 00:30:00+00:00
[2025-03-30T11:29:30.933+0000] {standard_task_runner.py:60} INFO - Started process 4453 to run task
[2025-03-30T11:29:30.943+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-02T00:30:00+00:00', '--job-id', '2201', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmptg78e_cb']
[2025-03-30T11:29:30.945+0000] {standard_task_runner.py:88} INFO - Job 2201: Subtask create_table
[2025-03-30T11:29:30.958+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:29:30.995+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-02T00:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:29:31.055+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T00:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-02T00:30:00+00:00'
[2025-03-30T11:29:31.061+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:29:31.062+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:29:31.063+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:29:31.064+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:29:31.079+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241002T003000, start_date=20250330T112930, end_date=20250330T112931
[2025-03-30T11:29:31.122+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:29:31.152+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:34:21.638+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-02T00:30:00+00:00 [queued]>
[2025-03-30T11:34:21.647+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-02T00:30:00+00:00 [queued]>
[2025-03-30T11:34:21.648+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:34:21.663+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-02 00:30:00+00:00
[2025-03-30T11:34:21.669+0000] {standard_task_runner.py:60} INFO - Started process 5907 to run task
[2025-03-30T11:34:21.676+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-02T00:30:00+00:00', '--job-id', '2928', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmp9rsuifoq']
[2025-03-30T11:34:21.678+0000] {standard_task_runner.py:88} INFO - Job 2928: Subtask create_table
[2025-03-30T11:34:21.689+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:34:21.741+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-02T00:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:34:21.855+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T00:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-02T00:30:00+00:00'
[2025-03-30T11:34:21.863+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:34:21.865+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:34:21.865+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:34:21.866+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:34:21.881+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241002T003000, start_date=20250330T113421, end_date=20250330T113421
[2025-03-30T11:34:21.941+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:34:21.974+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:41:58.698+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-02T00:30:00+00:00 [queued]>
[2025-03-30T11:41:58.709+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-02T00:30:00+00:00 [queued]>
[2025-03-30T11:41:58.710+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:41:58.723+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-02 00:30:00+00:00
[2025-03-30T11:41:58.730+0000] {standard_task_runner.py:60} INFO - Started process 7251 to run task
[2025-03-30T11:41:58.739+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-02T00:30:00+00:00', '--job-id', '3600', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpmp2ihpvw']
[2025-03-30T11:41:58.740+0000] {standard_task_runner.py:88} INFO - Job 3600: Subtask create_table
[2025-03-30T11:41:58.755+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:41:58.801+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-02T00:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:41:58.898+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T00:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-02T00:30:00+00:00'
[2025-03-30T11:41:58.906+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:41:58.907+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:41:58.907+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:41:58.907+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:41:58.917+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241002T003000, start_date=20250330T114158, end_date=20250330T114158
[2025-03-30T11:41:58.960+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:41:58.999+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
