[2025-03-30T11:12:27.317+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T16:00:00+00:00 [queued]>
[2025-03-30T11:12:27.326+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T16:00:00+00:00 [queued]>
[2025-03-30T11:12:27.327+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:12:27.343+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-05 16:00:00+00:00
[2025-03-30T11:12:27.355+0000] {standard_task_runner.py:60} INFO - Started process 1376 to run task
[2025-03-30T11:12:27.362+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-05T16:00:00+00:00', '--job-id', '662', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpyzmksvkz']
[2025-03-30T11:12:27.366+0000] {standard_task_runner.py:88} INFO - Job 662: Subtask create_table
[2025-03-30T11:12:27.389+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:12:27.435+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T16:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:12:27.538+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-05T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-05T16:00:00+00:00'
[2025-03-30T11:12:27.544+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:12:27.545+0000] {inout_data.py:124} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:12:27.546+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:12:27.546+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:12:27.558+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241005T160000, start_date=20250330T111227, end_date=20250330T111227
[2025-03-30T11:12:27.585+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:12:27.602+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:19:03.397+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T16:00:00+00:00 [queued]>
[2025-03-30T11:19:03.422+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T16:00:00+00:00 [queued]>
[2025-03-30T11:19:03.426+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:19:03.486+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-05 16:00:00+00:00
[2025-03-30T11:19:03.497+0000] {standard_task_runner.py:60} INFO - Started process 3228 to run task
[2025-03-30T11:19:03.523+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-05T16:00:00+00:00', '--job-id', '1588', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmptw_wuobo']
[2025-03-30T11:19:03.527+0000] {standard_task_runner.py:88} INFO - Job 1588: Subtask create_table
[2025-03-30T11:19:03.581+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:19:03.645+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T16:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:19:03.777+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-05T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-05T16:00:00+00:00'
[2025-03-30T11:19:03.783+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:19:03.786+0000] {inout_data.py:117} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:19:03.787+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:19:03.788+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:19:03.810+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241005T160000, start_date=20250330T111903, end_date=20250330T111903
[2025-03-30T11:19:03.857+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:19:03.909+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:31:14.088+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T16:00:00+00:00 [queued]>
[2025-03-30T11:31:14.104+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T16:00:00+00:00 [queued]>
[2025-03-30T11:31:14.104+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:31:14.120+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-05 16:00:00+00:00
[2025-03-30T11:31:14.126+0000] {standard_task_runner.py:60} INFO - Started process 5148 to run task
[2025-03-30T11:31:14.131+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-05T16:00:00+00:00', '--job-id', '2548', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmp60c714wx']
[2025-03-30T11:31:14.133+0000] {standard_task_runner.py:88} INFO - Job 2548: Subtask create_table
[2025-03-30T11:31:14.147+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:31:14.197+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T16:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:31:14.271+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-05T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-05T16:00:00+00:00'
[2025-03-30T11:31:14.279+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:31:14.281+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:31:14.282+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:31:14.283+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:31:14.301+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241005T160000, start_date=20250330T113114, end_date=20250330T113114
[2025-03-30T11:31:14.352+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:31:14.379+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
