[2025-03-30T11:13:34.937+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-07T20:30:00+00:00 [queued]>
[2025-03-30T11:13:34.960+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-07T20:30:00+00:00 [queued]>
[2025-03-30T11:13:34.962+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:13:34.984+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-07 20:30:00+00:00
[2025-03-30T11:13:34.989+0000] {standard_task_runner.py:60} INFO - Started process 1795 to run task
[2025-03-30T11:13:35.010+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-07T20:30:00+00:00', '--job-id', '870', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmptk1hz1bu']
[2025-03-30T11:13:35.015+0000] {standard_task_runner.py:88} INFO - Job 870: Subtask create_table
[2025-03-30T11:13:35.040+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:13:35.118+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-07T20:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:13:35.244+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-07T20:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-07T20:30:00+00:00'
[2025-03-30T11:13:35.252+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:13:35.253+0000] {inout_data.py:124} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:13:35.255+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:13:35.256+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:13:35.272+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241007T203000, start_date=20250330T111334, end_date=20250330T111335
[2025-03-30T11:13:35.317+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:13:35.471+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:20:20.782+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-07T20:30:00+00:00 [queued]>
[2025-03-30T11:20:20.794+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-07T20:30:00+00:00 [queued]>
[2025-03-30T11:20:20.796+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:20:20.810+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-07 20:30:00+00:00
[2025-03-30T11:20:20.822+0000] {standard_task_runner.py:60} INFO - Started process 3651 to run task
[2025-03-30T11:20:20.825+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-07T20:30:00+00:00', '--job-id', '1800', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpjho_c_yk']
[2025-03-30T11:20:20.827+0000] {standard_task_runner.py:88} INFO - Job 1800: Subtask create_table
[2025-03-30T11:20:20.843+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:20:20.886+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-07T20:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:20:20.999+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-07T20:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-07T20:30:00+00:00'
[2025-03-30T11:20:21.002+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:20:21.004+0000] {inout_data.py:117} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:20:21.004+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:20:21.005+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:20:21.016+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241007T203000, start_date=20250330T112020, end_date=20250330T112021
[2025-03-30T11:20:21.047+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:20:21.067+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
