[2025-03-30T11:12:02.713+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-04T22:00:00+00:00 [queued]>
[2025-03-30T11:12:02.726+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-04T22:00:00+00:00 [queued]>
[2025-03-30T11:12:02.727+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:12:02.750+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-10-04 22:00:00+00:00
[2025-03-30T11:12:02.753+0000] {standard_task_runner.py:60} INFO - Started process 1246 to run task
[2025-03-30T11:12:02.758+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-10-04T22:00:00+00:00', '--job-id', '597', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpv53s_mma']
[2025-03-30T11:12:02.760+0000] {standard_task_runner.py:88} INFO - Job 597: Subtask ingest_dummy_data
[2025-03-30T11:12:02.781+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:12:02.818+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-04T22:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:12:02.860+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-04T22:00:00+00:00'
[2025-03-30T11:12:02.862+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:12:02.863+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:02-8774' for key 'PRIMARY'")
[2025-03-30T11:12:02.864+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:02-8774' for key 'PRIMARY'")
[2025-03-30T11:12:02.864+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:02-8774' for key 'PRIMARY'")
[2025-03-30T11:12:02.864+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:02-8774' for key 'PRIMARY'")
[2025-03-30T11:12:02.865+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:02-8774' for key 'PRIMARY'")
[2025-03-30T11:12:02.865+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:02-8774' for key 'PRIMARY'")
[2025-03-30T11:12:02.866+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:02-8774' for key 'PRIMARY'")
[2025-03-30T11:12:02.866+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:02-8774' for key 'PRIMARY'")
[2025-03-30T11:12:02.866+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:02-8774' for key 'PRIMARY'")
[2025-03-30T11:12:02.867+0000] {inout_data.py:159} INFO - Ingested 10 rows of dummy data.
[2025-03-30T11:12:02.867+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:12:02.867+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:12:02.874+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20241004T220000, start_date=20250330T111202, end_date=20250330T111202
[2025-03-30T11:12:02.897+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:12:02.906+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:18:38.176+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-04T22:00:00+00:00 [queued]>
[2025-03-30T11:18:38.186+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-04T22:00:00+00:00 [queued]>
[2025-03-30T11:18:38.189+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:18:38.208+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-10-04 22:00:00+00:00
[2025-03-30T11:18:38.239+0000] {standard_task_runner.py:60} INFO - Started process 3104 to run task
[2025-03-30T11:18:38.264+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-10-04T22:00:00+00:00', '--job-id', '1525', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpk_8po9uy']
[2025-03-30T11:18:38.268+0000] {standard_task_runner.py:88} INFO - Job 1525: Subtask ingest_dummy_data
[2025-03-30T11:18:38.296+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:18:38.368+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-04T22:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:18:38.453+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-04T22:00:00+00:00'
[2025-03-30T11:18:38.458+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:18:38.461+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:18:38-5311' for key 'PRIMARY'")
[2025-03-30T11:18:38.462+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:18:38-5311' for key 'PRIMARY'")
[2025-03-30T11:18:38.463+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:18:38-5311' for key 'PRIMARY'")
[2025-03-30T11:18:38.464+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:18:38-5311' for key 'PRIMARY'")
[2025-03-30T11:18:38.464+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:18:38-5311' for key 'PRIMARY'")
[2025-03-30T11:18:38.465+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:18:38-5311' for key 'PRIMARY'")
[2025-03-30T11:18:38.466+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:18:38-5311' for key 'PRIMARY'")
[2025-03-30T11:18:38.467+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:18:38-5311' for key 'PRIMARY'")
[2025-03-30T11:18:38.470+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:18:38-5311' for key 'PRIMARY'")
[2025-03-30T11:18:38.471+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:18:38-5311' for key 'PRIMARY'")
[2025-03-30T11:18:38.472+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:18:38-5311' for key 'PRIMARY'")
[2025-03-30T11:18:38.473+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:18:38-5311' for key 'PRIMARY'")
[2025-03-30T11:18:38.474+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:18:38-5311' for key 'PRIMARY'")
[2025-03-30T11:18:38.475+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:18:38-5311' for key 'PRIMARY'")
[2025-03-30T11:18:38.475+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:18:38-5311' for key 'PRIMARY'")
[2025-03-30T11:18:38.477+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:18:38-5311' for key 'PRIMARY'")
[2025-03-30T11:18:38.477+0000] {inout_data.py:152} INFO - Ingested 17 rows of dummy data.
[2025-03-30T11:18:38.478+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:18:38.478+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:18:38.486+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20241004T220000, start_date=20250330T111838, end_date=20250330T111838
[2025-03-30T11:18:38.524+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:18:38.744+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:30:53.226+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-04T22:00:00+00:00 [queued]>
[2025-03-30T11:30:53.243+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-04T22:00:00+00:00 [queued]>
[2025-03-30T11:30:53.244+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:30:53.260+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-10-04 22:00:00+00:00
[2025-03-30T11:30:53.266+0000] {standard_task_runner.py:60} INFO - Started process 5022 to run task
[2025-03-30T11:30:53.270+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-10-04T22:00:00+00:00', '--job-id', '2486', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpsa7lbj0z']
[2025-03-30T11:30:53.273+0000] {standard_task_runner.py:88} INFO - Job 2486: Subtask ingest_dummy_data
[2025-03-30T11:30:53.301+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:30:53.363+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-04T22:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:30:53.451+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-04T22:00:00+00:00'
[2025-03-30T11:30:53.458+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:30:53.458+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:30:53.460+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:30:53.461+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:30:53.462+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:30:53.463+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:30:53.465+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:30:53.466+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:30:53.466+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:30:53.467+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:30:53.468+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:30:53.469+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:30:53.470+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:30:53.472+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:30:53.474+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:30:53.477+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:30:53.478+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:30:53.479+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:30:53.480+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:30:53.481+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:30:53.481+0000] {inout_data.py:87} INFO - Ingested 19 rows of dummy data for 2024-10-04 22:00:00+00:00.
[2025-03-30T11:30:53.482+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:30:53.482+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:30:53.510+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20241004T220000, start_date=20250330T113053, end_date=20250330T113053
[2025-03-30T11:30:53.537+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:30:53.571+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
