[2025-03-30T11:13:45.178+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-08T02:30:00+00:00 [queued]>
[2025-03-30T11:13:45.190+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-08T02:30:00+00:00 [queued]>
[2025-03-30T11:13:45.190+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:13:45.202+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-08 02:30:00+00:00
[2025-03-30T11:13:45.205+0000] {standard_task_runner.py:60} INFO - Started process 1850 to run task
[2025-03-30T11:13:45.209+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-08T02:30:00+00:00', '--job-id', '899', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmp_2zxj962']
[2025-03-30T11:13:45.211+0000] {standard_task_runner.py:88} INFO - Job 899: Subtask create_table
[2025-03-30T11:13:45.237+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:13:45.289+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-08T02:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:13:45.379+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T02:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-08T02:30:00+00:00'
[2025-03-30T11:13:45.388+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:13:45.389+0000] {inout_data.py:124} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:13:45.390+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:13:45.390+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:13:45.401+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241008T023000, start_date=20250330T111345, end_date=20250330T111345
[2025-03-30T11:13:45.434+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:13:45.467+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:20:26.590+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-08T02:30:00+00:00 [queued]>
[2025-03-30T11:20:26.616+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-08T02:30:00+00:00 [queued]>
[2025-03-30T11:20:26.617+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:20:26.653+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-08 02:30:00+00:00
[2025-03-30T11:20:26.659+0000] {standard_task_runner.py:60} INFO - Started process 3696 to run task
[2025-03-30T11:20:26.674+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-08T02:30:00+00:00', '--job-id', '1822', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpdzw5o0s6']
[2025-03-30T11:20:26.677+0000] {standard_task_runner.py:88} INFO - Job 1822: Subtask create_table
[2025-03-30T11:20:26.710+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:20:26.868+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-08T02:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:20:27.178+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T02:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-08T02:30:00+00:00'
[2025-03-30T11:20:27.226+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:20:27.230+0000] {inout_data.py:117} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:20:27.233+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:20:27.236+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:20:27.297+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241008T023000, start_date=20250330T112026, end_date=20250330T112027
[2025-03-30T11:20:27.370+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:20:27.510+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
