[2025-03-30T11:11:58.380+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T20:00:00+00:00 [queued]>
[2025-03-30T11:11:58.399+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T20:00:00+00:00 [queued]>
[2025-03-30T11:11:58.399+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:11:58.445+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-04 20:00:00+00:00
[2025-03-30T11:11:58.452+0000] {standard_task_runner.py:60} INFO - Started process 1215 to run task
[2025-03-30T11:11:58.458+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-04T20:00:00+00:00', '--job-id', '581', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmp_866bwio']
[2025-03-30T11:11:58.460+0000] {standard_task_runner.py:88} INFO - Job 581: Subtask create_table
[2025-03-30T11:11:58.491+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:11:58.556+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T20:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:11:58.708+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T20:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-04T20:00:00+00:00'
[2025-03-30T11:11:58.715+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:11:58.716+0000] {inout_data.py:124} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:11:58.718+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:11:58.719+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:11:58.731+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241004T200000, start_date=20250330T111158, end_date=20250330T111158
[2025-03-30T11:11:58.779+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:11:58.806+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:18:31.633+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T20:00:00+00:00 [queued]>
[2025-03-30T11:18:31.672+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T20:00:00+00:00 [queued]>
[2025-03-30T11:18:31.674+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:18:31.718+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-04 20:00:00+00:00
[2025-03-30T11:18:31.726+0000] {standard_task_runner.py:60} INFO - Started process 3070 to run task
[2025-03-30T11:18:31.739+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-04T20:00:00+00:00', '--job-id', '1509', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmp__59odzf']
[2025-03-30T11:18:31.745+0000] {standard_task_runner.py:88} INFO - Job 1509: Subtask create_table
[2025-03-30T11:18:31.775+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:18:31.830+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T20:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:18:31.941+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T20:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-04T20:00:00+00:00'
[2025-03-30T11:18:31.949+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:18:31.952+0000] {inout_data.py:117} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:18:31.953+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:18:31.954+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:18:31.967+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241004T200000, start_date=20250330T111831, end_date=20250330T111831
[2025-03-30T11:18:32.041+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:18:32.089+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:30:48.014+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T20:00:00+00:00 [queued]>
[2025-03-30T11:30:48.027+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T20:00:00+00:00 [queued]>
[2025-03-30T11:30:48.027+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:30:48.057+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-04 20:00:00+00:00
[2025-03-30T11:30:48.065+0000] {standard_task_runner.py:60} INFO - Started process 4989 to run task
[2025-03-30T11:30:48.079+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-04T20:00:00+00:00', '--job-id', '2468', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpsueaphfd']
[2025-03-30T11:30:48.088+0000] {standard_task_runner.py:88} INFO - Job 2468: Subtask create_table
[2025-03-30T11:30:48.108+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:30:48.183+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T20:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:30:48.380+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T20:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-04T20:00:00+00:00'
[2025-03-30T11:30:48.394+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:30:48.396+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:30:48.398+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:30:48.400+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:30:48.423+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241004T200000, start_date=20250330T113048, end_date=20250330T113048
[2025-03-30T11:30:48.511+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:30:48.572+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
