[2025-03-30T11:11:42.449+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T08:30:00+00:00 [queued]>
[2025-03-30T11:11:42.469+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T08:30:00+00:00 [queued]>
[2025-03-30T11:11:42.470+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:11:42.489+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-04 08:30:00+00:00
[2025-03-30T11:11:42.500+0000] {standard_task_runner.py:60} INFO - Started process 1122 to run task
[2025-03-30T11:11:42.509+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-04T08:30:00+00:00', '--job-id', '535', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmp8ytdfi2v']
[2025-03-30T11:11:42.511+0000] {standard_task_runner.py:88} INFO - Job 535: Subtask create_table
[2025-03-30T11:11:42.545+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:11:42.612+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T08:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:11:42.751+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T08:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-04T08:30:00+00:00'
[2025-03-30T11:11:42.762+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:11:42.763+0000] {inout_data.py:124} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:11:42.764+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:11:42.764+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:11:42.781+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241004T083000, start_date=20250330T111142, end_date=20250330T111142
[2025-03-30T11:11:42.814+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:11:42.843+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:18:14.150+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T08:30:00+00:00 [queued]>
[2025-03-30T11:18:14.162+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T08:30:00+00:00 [queued]>
[2025-03-30T11:18:14.163+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:18:14.189+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-04 08:30:00+00:00
[2025-03-30T11:18:14.198+0000] {standard_task_runner.py:60} INFO - Started process 2974 to run task
[2025-03-30T11:18:14.212+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-04T08:30:00+00:00', '--job-id', '1462', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmp9glgxmbc']
[2025-03-30T11:18:14.215+0000] {standard_task_runner.py:88} INFO - Job 1462: Subtask create_table
[2025-03-30T11:18:14.254+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:18:14.377+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T08:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:18:14.584+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T08:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-04T08:30:00+00:00'
[2025-03-30T11:18:14.625+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:18:14.632+0000] {inout_data.py:117} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:18:14.634+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:18:14.638+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:18:14.685+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241004T083000, start_date=20250330T111814, end_date=20250330T111814
[2025-03-30T11:18:14.767+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:18:14.880+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:30:34.503+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T08:30:00+00:00 [queued]>
[2025-03-30T11:30:34.517+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T08:30:00+00:00 [queued]>
[2025-03-30T11:30:34.519+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:30:34.542+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-04 08:30:00+00:00
[2025-03-30T11:30:34.550+0000] {standard_task_runner.py:60} INFO - Started process 4898 to run task
[2025-03-30T11:30:34.557+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-04T08:30:00+00:00', '--job-id', '2423', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpjcat9rqj']
[2025-03-30T11:30:34.559+0000] {standard_task_runner.py:88} INFO - Job 2423: Subtask create_table
[2025-03-30T11:30:34.578+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:30:34.625+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T08:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:30:34.744+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T08:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-04T08:30:00+00:00'
[2025-03-30T11:30:34.750+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:30:34.751+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:30:34.752+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:30:34.752+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:30:34.772+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241004T083000, start_date=20250330T113034, end_date=20250330T113034
[2025-03-30T11:30:34.820+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:30:34.861+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
