[2025-03-30T11:09:39.110+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T16:30:00+00:00 [queued]>
[2025-03-30T11:09:39.125+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T16:30:00+00:00 [queued]>
[2025-03-30T11:09:39.128+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:09:39.199+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-30 16:30:00+00:00
[2025-03-30T11:09:39.222+0000] {standard_task_runner.py:60} INFO - Started process 421 to run task
[2025-03-30T11:09:39.241+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-30T16:30:00+00:00', '--job-id', '184', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmptr6bz2iv']
[2025-03-30T11:09:39.243+0000] {standard_task_runner.py:88} INFO - Job 184: Subtask create_table
[2025-03-30T11:09:39.291+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:09:39.376+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T16:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:09:39.489+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T16:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T16:30:00+00:00'
[2025-03-30T11:09:39.499+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:09:39.501+0000] {inout_data.py:124} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:09:39.502+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:09:39.503+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:09:39.527+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240930T163000, start_date=20250330T110939, end_date=20250330T110939
[2025-03-30T11:09:39.601+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:09:39.660+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:16:15.976+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T16:30:00+00:00 [queued]>
[2025-03-30T11:16:15.989+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T16:30:00+00:00 [queued]>
[2025-03-30T11:16:15.990+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:16:16.016+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-30 16:30:00+00:00
[2025-03-30T11:16:16.021+0000] {standard_task_runner.py:60} INFO - Started process 2271 to run task
[2025-03-30T11:16:16.025+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-30T16:30:00+00:00', '--job-id', '1110', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpuon72fyd']
[2025-03-30T11:16:16.027+0000] {standard_task_runner.py:88} INFO - Job 1110: Subtask create_table
[2025-03-30T11:16:16.035+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:16:16.075+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T16:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:16:16.190+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T16:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T16:30:00+00:00'
[2025-03-30T11:16:16.196+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:16:16.198+0000] {inout_data.py:117} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:16:16.199+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:16:16.200+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:16:16.213+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240930T163000, start_date=20250330T111615, end_date=20250330T111616
[2025-03-30T11:16:16.246+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:16:16.273+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:28:50.749+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T16:30:00+00:00 [queued]>
[2025-03-30T11:28:50.811+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T16:30:00+00:00 [queued]>
[2025-03-30T11:28:50.811+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:28:50.850+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-30 16:30:00+00:00
[2025-03-30T11:28:50.862+0000] {standard_task_runner.py:60} INFO - Started process 4193 to run task
[2025-03-30T11:28:50.876+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-30T16:30:00+00:00', '--job-id', '2071', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpb2h1stel']
[2025-03-30T11:28:50.878+0000] {standard_task_runner.py:88} INFO - Job 2071: Subtask create_table
[2025-03-30T11:28:50.922+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:28:51.006+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T16:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:28:51.164+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T16:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T16:30:00+00:00'
[2025-03-30T11:28:51.177+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:28:51.180+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:28:51.182+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:28:51.184+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:28:51.206+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240930T163000, start_date=20250330T112850, end_date=20250330T112851
[2025-03-30T11:28:51.276+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:28:51.343+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:33:25.256+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T16:30:00+00:00 [queued]>
[2025-03-30T11:33:25.270+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T16:30:00+00:00 [queued]>
[2025-03-30T11:33:25.271+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:33:25.288+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-30 16:30:00+00:00
[2025-03-30T11:33:25.291+0000] {standard_task_runner.py:60} INFO - Started process 5643 to run task
[2025-03-30T11:33:25.294+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-30T16:30:00+00:00', '--job-id', '2797', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmprr21pffj']
[2025-03-30T11:33:25.295+0000] {standard_task_runner.py:88} INFO - Job 2797: Subtask create_table
[2025-03-30T11:33:25.303+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:33:25.323+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T16:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:33:25.386+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T16:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T16:30:00+00:00'
[2025-03-30T11:33:25.391+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:33:25.391+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:33:25.391+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:33:25.392+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:33:25.402+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240930T163000, start_date=20250330T113325, end_date=20250330T113325
[2025-03-30T11:33:25.475+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:33:25.500+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:39:03.062+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T16:30:00+00:00 [queued]>
[2025-03-30T11:39:03.098+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T16:30:00+00:00 [queued]>
[2025-03-30T11:39:03.100+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:39:03.154+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-30 16:30:00+00:00
[2025-03-30T11:39:03.175+0000] {standard_task_runner.py:60} INFO - Started process 6550 to run task
[2025-03-30T11:39:03.203+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-30T16:30:00+00:00', '--job-id', '3249', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpgrtnwckb']
[2025-03-30T11:39:03.209+0000] {standard_task_runner.py:88} INFO - Job 3249: Subtask create_table
[2025-03-30T11:39:03.270+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:39:03.432+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T16:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:39:03.701+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T16:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T16:30:00+00:00'
[2025-03-30T11:39:03.719+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:39:03.721+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:39:03.722+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:39:03.723+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:39:03.756+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240930T163000, start_date=20250330T113903, end_date=20250330T113903
[2025-03-30T11:39:03.799+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:39:03.991+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:41:05.451+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T16:30:00+00:00 [queued]>
[2025-03-30T11:41:05.474+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T16:30:00+00:00 [queued]>
[2025-03-30T11:41:05.476+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:41:05.509+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-30 16:30:00+00:00
[2025-03-30T11:41:05.526+0000] {standard_task_runner.py:60} INFO - Started process 6992 to run task
[2025-03-30T11:41:05.541+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-30T16:30:00+00:00', '--job-id', '3471', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmp5cqm923s']
[2025-03-30T11:41:05.543+0000] {standard_task_runner.py:88} INFO - Job 3471: Subtask create_table
[2025-03-30T11:41:05.570+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:41:05.619+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T16:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:41:05.699+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T16:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T16:30:00+00:00'
[2025-03-30T11:41:05.705+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:41:05.707+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:41:05.708+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:41:05.708+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:41:05.718+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240930T163000, start_date=20250330T114105, end_date=20250330T114105
[2025-03-30T11:41:05.764+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:41:05.778+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
