[2025-03-30T11:09:39.456+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T17:00:00+00:00 [queued]>
[2025-03-30T11:09:39.469+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T17:00:00+00:00 [queued]>
[2025-03-30T11:09:39.470+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:09:39.492+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-30 17:00:00+00:00
[2025-03-30T11:09:39.503+0000] {standard_task_runner.py:60} INFO - Started process 424 to run task
[2025-03-30T11:09:39.513+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-30T17:00:00+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpj34su7j9']
[2025-03-30T11:09:39.515+0000] {standard_task_runner.py:88} INFO - Job 186: Subtask create_table
[2025-03-30T11:09:39.539+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:09:39.615+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T17:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:09:39.751+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T17:00:00+00:00'
[2025-03-30T11:09:39.760+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:09:39.761+0000] {inout_data.py:124} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:09:39.761+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:09:39.761+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:09:39.777+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240930T170000, start_date=20250330T110939, end_date=20250330T110939
[2025-03-30T11:09:39.824+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:09:39.856+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:16:16.187+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T17:00:00+00:00 [queued]>
[2025-03-30T11:16:16.199+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T17:00:00+00:00 [queued]>
[2025-03-30T11:16:16.200+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:16:16.219+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-30 17:00:00+00:00
[2025-03-30T11:16:16.224+0000] {standard_task_runner.py:60} INFO - Started process 2275 to run task
[2025-03-30T11:16:16.229+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-30T17:00:00+00:00', '--job-id', '1112', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmp7i__v5zf']
[2025-03-30T11:16:16.232+0000] {standard_task_runner.py:88} INFO - Job 1112: Subtask create_table
[2025-03-30T11:16:16.253+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:16:16.293+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T17:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:16:16.387+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T17:00:00+00:00'
[2025-03-30T11:16:16.404+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:16:16.407+0000] {inout_data.py:117} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:16:16.408+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:16:16.409+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:16:16.425+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240930T170000, start_date=20250330T111616, end_date=20250330T111616
[2025-03-30T11:16:16.499+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:16:16.588+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:28:51.372+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T17:00:00+00:00 [queued]>
[2025-03-30T11:28:51.399+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T17:00:00+00:00 [queued]>
[2025-03-30T11:28:51.400+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:28:51.429+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-30 17:00:00+00:00
[2025-03-30T11:28:51.435+0000] {standard_task_runner.py:60} INFO - Started process 4198 to run task
[2025-03-30T11:28:51.446+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-30T17:00:00+00:00', '--job-id', '2073', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmphthcmm13']
[2025-03-30T11:28:51.449+0000] {standard_task_runner.py:88} INFO - Job 2073: Subtask create_table
[2025-03-30T11:28:51.517+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:28:51.627+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T17:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:28:51.929+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T17:00:00+00:00'
[2025-03-30T11:28:51.947+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:28:51.950+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:28:51.952+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:28:51.954+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:28:51.995+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240930T170000, start_date=20250330T112851, end_date=20250330T112851
[2025-03-30T11:28:52.085+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:28:52.184+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:33:25.666+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T17:00:00+00:00 [queued]>
[2025-03-30T11:33:25.682+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T17:00:00+00:00 [queued]>
[2025-03-30T11:33:25.683+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:33:25.711+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-30 17:00:00+00:00
[2025-03-30T11:33:25.725+0000] {standard_task_runner.py:60} INFO - Started process 5652 to run task
[2025-03-30T11:33:25.730+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-30T17:00:00+00:00', '--job-id', '2799', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmp60xoo4e1']
[2025-03-30T11:33:25.734+0000] {standard_task_runner.py:88} INFO - Job 2799: Subtask create_table
[2025-03-30T11:33:25.755+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:33:25.827+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T17:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:33:26.025+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T17:00:00+00:00'
[2025-03-30T11:33:26.035+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:33:26.037+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:33:26.038+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:33:26.038+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:33:26.055+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240930T170000, start_date=20250330T113325, end_date=20250330T113326
[2025-03-30T11:33:26.087+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:33:26.165+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:39:03.720+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T17:00:00+00:00 [queued]>
[2025-03-30T11:39:03.747+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T17:00:00+00:00 [queued]>
[2025-03-30T11:39:03.748+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:39:03.770+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-30 17:00:00+00:00
[2025-03-30T11:39:03.788+0000] {standard_task_runner.py:60} INFO - Started process 6553 to run task
[2025-03-30T11:39:03.794+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-30T17:00:00+00:00', '--job-id', '3252', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmppu5u9nuk']
[2025-03-30T11:39:03.799+0000] {standard_task_runner.py:88} INFO - Job 3252: Subtask create_table
[2025-03-30T11:39:03.840+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:39:03.992+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T17:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:39:04.138+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T17:00:00+00:00'
[2025-03-30T11:39:04.154+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:39:04.157+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:39:04.158+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:39:04.159+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:39:04.177+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240930T170000, start_date=20250330T113903, end_date=20250330T113904
[2025-03-30T11:39:04.229+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:39:04.303+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:41:10.925+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T17:00:00+00:00 [queued]>
[2025-03-30T11:41:10.946+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T17:00:00+00:00 [queued]>
[2025-03-30T11:41:10.947+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:41:11.010+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-30 17:00:00+00:00
[2025-03-30T11:41:11.031+0000] {standard_task_runner.py:60} INFO - Started process 7002 to run task
[2025-03-30T11:41:11.039+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-30T17:00:00+00:00', '--job-id', '3475', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpwkzw9r7d']
[2025-03-30T11:41:11.049+0000] {standard_task_runner.py:88} INFO - Job 3475: Subtask create_table
[2025-03-30T11:41:11.110+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:41:11.315+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T17:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:41:11.657+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T17:00:00+00:00'
[2025-03-30T11:41:11.672+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:41:11.676+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:41:11.679+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:41:11.681+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:41:11.706+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240930T170000, start_date=20250330T114110, end_date=20250330T114111
[2025-03-30T11:41:11.859+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:41:12.070+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
