[2025-03-30T11:11:09.471+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-03T08:30:00+00:00 [queued]>
[2025-03-30T11:11:09.488+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-03T08:30:00+00:00 [queued]>
[2025-03-30T11:11:09.489+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:11:09.516+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-03 08:30:00+00:00
[2025-03-30T11:11:09.524+0000] {standard_task_runner.py:60} INFO - Started process 938 to run task
[2025-03-30T11:11:09.534+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-03T08:30:00+00:00', '--job-id', '443', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpqipy00eu']
[2025-03-30T11:11:09.537+0000] {standard_task_runner.py:88} INFO - Job 443: Subtask create_table
[2025-03-30T11:11:09.570+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:11:09.623+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-03T08:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:11:09.712+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T08:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-03T08:30:00+00:00'
[2025-03-30T11:11:09.719+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:11:09.720+0000] {inout_data.py:124} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:11:09.721+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:11:09.721+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:11:09.742+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241003T083000, start_date=20250330T111109, end_date=20250330T111109
[2025-03-30T11:11:09.795+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:11:09.909+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:17:42.270+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-03T08:30:00+00:00 [queued]>
[2025-03-30T11:17:42.293+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-03T08:30:00+00:00 [queued]>
[2025-03-30T11:17:42.295+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:17:42.330+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-03 08:30:00+00:00
[2025-03-30T11:17:42.341+0000] {standard_task_runner.py:60} INFO - Started process 2786 to run task
[2025-03-30T11:17:42.348+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-03T08:30:00+00:00', '--job-id', '1367', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmp5j9yqsr4']
[2025-03-30T11:17:42.350+0000] {standard_task_runner.py:88} INFO - Job 1367: Subtask create_table
[2025-03-30T11:17:42.372+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:17:42.429+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-03T08:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:17:42.531+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T08:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-03T08:30:00+00:00'
[2025-03-30T11:17:42.538+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:17:42.539+0000] {inout_data.py:117} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:17:42.539+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:17:42.540+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:17:42.557+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241003T083000, start_date=20250330T111742, end_date=20250330T111742
[2025-03-30T11:17:42.618+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:17:42.649+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:30:07.056+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-03T08:30:00+00:00 [queued]>
[2025-03-30T11:30:07.071+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-03T08:30:00+00:00 [queued]>
[2025-03-30T11:30:07.072+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:30:07.088+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-03 08:30:00+00:00
[2025-03-30T11:30:07.097+0000] {standard_task_runner.py:60} INFO - Started process 4707 to run task
[2025-03-30T11:30:07.108+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-03T08:30:00+00:00', '--job-id', '2328', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmp4vtb31k6']
[2025-03-30T11:30:07.113+0000] {standard_task_runner.py:88} INFO - Job 2328: Subtask create_table
[2025-03-30T11:30:07.151+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:30:07.222+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-03T08:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:30:07.351+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T08:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-03T08:30:00+00:00'
[2025-03-30T11:30:07.367+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:30:07.368+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:30:07.369+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:30:07.371+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:30:07.398+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241003T083000, start_date=20250330T113007, end_date=20250330T113007
[2025-03-30T11:30:07.452+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:30:07.416+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:35:01.585+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-03T08:30:00+00:00 [queued]>
[2025-03-30T11:35:01.603+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-03T08:30:00+00:00 [queued]>
[2025-03-30T11:35:01.604+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:35:01.618+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-03 08:30:00+00:00
[2025-03-30T11:35:01.623+0000] {standard_task_runner.py:60} INFO - Started process 6162 to run task
[2025-03-30T11:35:01.626+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-03T08:30:00+00:00', '--job-id', '3056', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpwfjxiil7']
[2025-03-30T11:35:01.627+0000] {standard_task_runner.py:88} INFO - Job 3056: Subtask create_table
[2025-03-30T11:35:01.635+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:35:01.659+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-03T08:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:35:01.712+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T08:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-03T08:30:00+00:00'
[2025-03-30T11:35:01.713+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:35:01.714+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:35:01.714+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:35:01.714+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:35:01.719+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241003T083000, start_date=20250330T113501, end_date=20250330T113501
[2025-03-30T11:35:01.767+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:35:01.780+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
