[2025-03-30T11:12:13.396+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T07:30:00+00:00 [queued]>
[2025-03-30T11:12:13.414+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T07:30:00+00:00 [queued]>
[2025-03-30T11:12:13.416+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:12:13.462+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-05 07:30:00+00:00
[2025-03-30T11:12:13.475+0000] {standard_task_runner.py:60} INFO - Started process 1309 to run task
[2025-03-30T11:12:13.488+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-05T07:30:00+00:00', '--job-id', '628', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmp_lwio5h6']
[2025-03-30T11:12:13.491+0000] {standard_task_runner.py:88} INFO - Job 628: Subtask create_table
[2025-03-30T11:12:13.512+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:12:13.607+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T07:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:12:13.726+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-05T07:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-05T07:30:00+00:00'
[2025-03-30T11:12:13.733+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:12:13.734+0000] {inout_data.py:124} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:12:13.735+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:12:13.736+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:12:13.745+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241005T073000, start_date=20250330T111213, end_date=20250330T111213
[2025-03-30T11:12:13.785+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:12:13.812+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:18:51.288+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T07:30:00+00:00 [queued]>
[2025-03-30T11:18:51.334+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T07:30:00+00:00 [queued]>
[2025-03-30T11:18:51.336+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:18:51.402+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-05 07:30:00+00:00
[2025-03-30T11:18:51.411+0000] {standard_task_runner.py:60} INFO - Started process 3161 to run task
[2025-03-30T11:18:51.429+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-05T07:30:00+00:00', '--job-id', '1555', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpwuvvys7e']
[2025-03-30T11:18:51.433+0000] {standard_task_runner.py:88} INFO - Job 1555: Subtask create_table
[2025-03-30T11:18:51.502+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:18:51.619+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T07:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:18:51.838+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-05T07:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-05T07:30:00+00:00'
[2025-03-30T11:18:51.852+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:18:51.853+0000] {inout_data.py:117} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:18:51.854+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:18:51.855+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:18:51.871+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241005T073000, start_date=20250330T111851, end_date=20250330T111851
[2025-03-30T11:18:51.925+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:18:52.016+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:31:03.547+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T07:30:00+00:00 [queued]>
[2025-03-30T11:31:03.561+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T07:30:00+00:00 [queued]>
[2025-03-30T11:31:03.562+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:31:03.583+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-05 07:30:00+00:00
[2025-03-30T11:31:03.590+0000] {standard_task_runner.py:60} INFO - Started process 5079 to run task
[2025-03-30T11:31:03.598+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-05T07:30:00+00:00', '--job-id', '2514', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpqqcynd06']
[2025-03-30T11:31:03.600+0000] {standard_task_runner.py:88} INFO - Job 2514: Subtask create_table
[2025-03-30T11:31:03.617+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:31:03.664+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-05T07:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:31:03.758+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-05T07:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-05T07:30:00+00:00'
[2025-03-30T11:31:03.767+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:31:03.768+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:31:03.769+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:31:03.769+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:31:03.782+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241005T073000, start_date=20250330T113103, end_date=20250330T113103
[2025-03-30T11:31:03.820+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:31:03.844+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
