[2025-03-30T11:10:55.282+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T23:30:00+00:00 [queued]>
[2025-03-30T11:10:55.291+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T23:30:00+00:00 [queued]>
[2025-03-30T11:10:55.293+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:10:55.308+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-10-02 23:30:00+00:00
[2025-03-30T11:10:55.312+0000] {standard_task_runner.py:60} INFO - Started process 869 to run task
[2025-03-30T11:10:55.315+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-10-02T23:30:00+00:00', '--job-id', '409', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpcylp1qyo']
[2025-03-30T11:10:55.317+0000] {standard_task_runner.py:88} INFO - Job 409: Subtask ingest_dummy_data
[2025-03-30T11:10:55.326+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:10:55.401+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T23:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:10:55.470+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T23:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-02T23:30:00+00:00'
[2025-03-30T11:10:55.473+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:10:55.474+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:55-2592' for key 'PRIMARY'")
[2025-03-30T11:10:55.475+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:55-2592' for key 'PRIMARY'")
[2025-03-30T11:10:55.475+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:55-2592' for key 'PRIMARY'")
[2025-03-30T11:10:55.476+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:55-2592' for key 'PRIMARY'")
[2025-03-30T11:10:55.476+0000] {inout_data.py:159} INFO - Ingested 5 rows of dummy data.
[2025-03-30T11:10:55.477+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:10:55.477+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:10:55.486+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20241002T233000, start_date=20250330T111055, end_date=20250330T111055
[2025-03-30T11:10:55.536+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:10:55.554+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:17:32.283+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T23:30:00+00:00 [queued]>
[2025-03-30T11:17:32.291+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T23:30:00+00:00 [queued]>
[2025-03-30T11:17:32.293+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:17:32.305+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-10-02 23:30:00+00:00
[2025-03-30T11:17:32.312+0000] {standard_task_runner.py:60} INFO - Started process 2722 to run task
[2025-03-30T11:17:32.322+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-10-02T23:30:00+00:00', '--job-id', '1336', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpeov_r1n0']
[2025-03-30T11:17:32.323+0000] {standard_task_runner.py:88} INFO - Job 1336: Subtask ingest_dummy_data
[2025-03-30T11:17:32.335+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:17:32.356+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T23:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:17:32.398+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T23:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-02T23:30:00+00:00'
[2025-03-30T11:17:32.400+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:17:32.401+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:17:32-8377' for key 'PRIMARY'")
[2025-03-30T11:17:32.401+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:17:32-8377' for key 'PRIMARY'")
[2025-03-30T11:17:32.402+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:17:32-8377' for key 'PRIMARY'")
[2025-03-30T11:17:32.402+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:17:32-8377' for key 'PRIMARY'")
[2025-03-30T11:17:32.402+0000] {inout_data.py:152} INFO - Ingested 5 rows of dummy data.
[2025-03-30T11:17:32.402+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:17:32.402+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:17:32.407+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20241002T233000, start_date=20250330T111732, end_date=20250330T111732
[2025-03-30T11:17:32.421+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:17:32.430+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:29:58.482+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T23:30:00+00:00 [queued]>
[2025-03-30T11:29:58.503+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T23:30:00+00:00 [queued]>
[2025-03-30T11:29:58.504+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:29:58.537+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-10-02 23:30:00+00:00
[2025-03-30T11:29:58.547+0000] {standard_task_runner.py:60} INFO - Started process 4652 to run task
[2025-03-30T11:29:58.559+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-10-02T23:30:00+00:00', '--job-id', '2300', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmp4w3pulky']
[2025-03-30T11:29:58.563+0000] {standard_task_runner.py:88} INFO - Job 2300: Subtask ingest_dummy_data
[2025-03-30T11:29:58.637+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:29:58.714+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T23:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:29:58.821+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T23:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-02T23:30:00+00:00'
[2025-03-30T11:29:58.837+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:29:58.840+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:29:58.842+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:29:58.843+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:29:58.844+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:29:58.847+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:29:58.850+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:29:58.851+0000] {inout_data.py:87} INFO - Ingested 6 rows of dummy data for 2024-10-02 23:30:00+00:00.
[2025-03-30T11:29:58.853+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:29:58.853+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:29:58.872+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20241002T233000, start_date=20250330T112958, end_date=20250330T112958
[2025-03-30T11:29:58.959+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:29:58.980+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:34:54.322+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T23:30:00+00:00 [queued]>
[2025-03-30T11:34:54.344+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T23:30:00+00:00 [queued]>
[2025-03-30T11:34:54.346+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:34:54.396+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-10-02 23:30:00+00:00
[2025-03-30T11:34:54.416+0000] {standard_task_runner.py:60} INFO - Started process 6099 to run task
[2025-03-30T11:34:54.439+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-10-02T23:30:00+00:00', '--job-id', '3023', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmp2pqz49hp']
[2025-03-30T11:34:54.452+0000] {standard_task_runner.py:88} INFO - Job 3023: Subtask ingest_dummy_data
[2025-03-30T11:34:54.567+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:34:54.691+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T23:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:34:54.922+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T23:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-02T23:30:00+00:00'
[2025-03-30T11:34:54.934+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:34:54.937+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 34, 54, 936517), 'timestamp': datetime.datetime(2024, 10, 2, 23, 45, tzinfo=datetime.timezone.utc), 'emp_id': 5031, 'employee_name': 'Employee82', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '5', 'function': 'IT', 'division': 'BSID', 'department': 'HRSD', 'section': '2'}
[2025-03-30T11:34:54.941+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:34:54.944+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 34, 54, 943446), 'timestamp': datetime.datetime(2024, 10, 2, 23, 59, tzinfo=datetime.timezone.utc), 'emp_id': 2410, 'employee_name': 'Employee70', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '2', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '1'}
[2025-03-30T11:34:54.947+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:34:54.951+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 34, 54, 951233), 'timestamp': datetime.datetime(2024, 10, 2, 23, 34, tzinfo=datetime.timezone.utc), 'emp_id': 5721, 'employee_name': 'Employee17', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '7', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '1'}
[2025-03-30T11:34:54.951+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:34:54.952+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 34, 54, 952498), 'timestamp': datetime.datetime(2024, 10, 2, 23, 44, tzinfo=datetime.timezone.utc), 'emp_id': 3028, 'employee_name': 'Employee74', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '4', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '2'}
[2025-03-30T11:34:54.953+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:34:54.954+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 34, 54, 954436), 'timestamp': datetime.datetime(2024, 10, 2, 23, 30, tzinfo=datetime.timezone.utc), 'emp_id': 3281, 'employee_name': 'Employee10', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '5', 'function': 'IT', 'division': 'BSID', 'department': 'HRSD', 'section': '2'}
[2025-03-30T11:34:54.956+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:34:54.960+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 34, 54, 960275), 'timestamp': datetime.datetime(2024, 10, 2, 23, 32, tzinfo=datetime.timezone.utc), 'emp_id': 8373, 'employee_name': 'Employee12', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '4', 'function': 'IT', 'division': 'AAPD', 'department': 'HRSD', 'section': '1'}
[2025-03-30T11:34:54.962+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:34:54.964+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 34, 54, 964141), 'timestamp': datetime.datetime(2024, 10, 2, 23, 33, tzinfo=datetime.timezone.utc), 'emp_id': 4362, 'employee_name': 'Employee11', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '7', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '1'}
[2025-03-30T11:34:54.967+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:34:54.968+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 34, 54, 967986), 'timestamp': datetime.datetime(2024, 10, 2, 23, 41, tzinfo=datetime.timezone.utc), 'emp_id': 9632, 'employee_name': 'Employee66', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '1', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '2'}
[2025-03-30T11:34:54.972+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:34:54.973+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 34, 54, 973661), 'timestamp': datetime.datetime(2024, 10, 2, 23, 55, tzinfo=datetime.timezone.utc), 'emp_id': 1664, 'employee_name': 'Employee19', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '6', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '1'}
[2025-03-30T11:34:54.974+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:34:54.975+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 34, 54, 975599), 'timestamp': datetime.datetime(2024, 10, 2, 23, 49, tzinfo=datetime.timezone.utc), 'emp_id': 4296, 'employee_name': 'Employee53', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '1', 'function': 'IT', 'division': 'AAPD', 'department': 'ML', 'section': '2'}
[2025-03-30T11:34:54.976+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:34:54.976+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 34, 54, 976835), 'timestamp': datetime.datetime(2024, 10, 2, 23, 43, tzinfo=datetime.timezone.utc), 'emp_id': 1215, 'employee_name': 'Employee62', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '2', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '1'}
[2025-03-30T11:34:54.978+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:34:54.979+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 34, 54, 979034), 'timestamp': datetime.datetime(2024, 10, 2, 23, 32, tzinfo=datetime.timezone.utc), 'emp_id': 1489, 'employee_name': 'Employee47', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '6', 'function': 'IT', 'division': 'AAPD', 'department': 'CAPD', 'section': '2'}
[2025-03-30T11:34:54.979+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:34:54.981+0000] {inout_data.py:88} INFO - Ingested 12 rows of dummy data for 2024-10-02 23:30:00+00:00.
[2025-03-30T11:34:54.982+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:34:54.983+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:34:55.010+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20241002T233000, start_date=20250330T113454, end_date=20250330T113455
[2025-03-30T11:34:55.072+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:34:55.110+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
