[2025-03-30T11:09:17.507+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T23:30:00+00:00 [queued]>
[2025-03-30T11:09:17.519+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T23:30:00+00:00 [queued]>
[2025-03-30T11:09:17.522+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:09:17.551+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-29 23:30:00+00:00
[2025-03-30T11:09:17.559+0000] {standard_task_runner.py:60} INFO - Started process 291 to run task
[2025-03-30T11:09:17.564+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-29T23:30:00+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpj7acyo1i']
[2025-03-30T11:09:17.568+0000] {standard_task_runner.py:88} INFO - Job 119: Subtask create_table
[2025-03-30T11:09:17.594+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:09:17.643+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T23:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:09:17.744+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T23:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-29T23:30:00+00:00'
[2025-03-30T11:09:17.749+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:09:17.752+0000] {inout_data.py:124} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:09:17.752+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:09:17.753+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:09:17.764+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240929T233000, start_date=20250330T110917, end_date=20250330T110917
[2025-03-30T11:09:17.835+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:09:17.887+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:15:55.561+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T23:30:00+00:00 [queued]>
[2025-03-30T11:15:55.585+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T23:30:00+00:00 [queued]>
[2025-03-30T11:15:55.586+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:15:55.602+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-29 23:30:00+00:00
[2025-03-30T11:15:55.618+0000] {standard_task_runner.py:60} INFO - Started process 2135 to run task
[2025-03-30T11:15:55.647+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-29T23:30:00+00:00', '--job-id', '1042', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpmthow4tq']
[2025-03-30T11:15:55.651+0000] {standard_task_runner.py:88} INFO - Job 1042: Subtask create_table
[2025-03-30T11:15:55.683+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:15:55.744+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T23:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:15:55.869+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T23:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-29T23:30:00+00:00'
[2025-03-30T11:15:55.880+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:15:55.881+0000] {inout_data.py:117} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:15:55.881+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:15:55.881+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:15:55.908+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240929T233000, start_date=20250330T111555, end_date=20250330T111555
[2025-03-30T11:15:55.978+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:15:56.018+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:28:28.422+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T23:30:00+00:00 [queued]>
[2025-03-30T11:28:28.438+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T23:30:00+00:00 [queued]>
[2025-03-30T11:28:28.439+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:28:28.451+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-29 23:30:00+00:00
[2025-03-30T11:28:28.455+0000] {standard_task_runner.py:60} INFO - Started process 4061 to run task
[2025-03-30T11:28:28.467+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-29T23:30:00+00:00', '--job-id', '2005', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpzs0efe3u']
[2025-03-30T11:28:28.469+0000] {standard_task_runner.py:88} INFO - Job 2005: Subtask create_table
[2025-03-30T11:28:28.492+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:28:28.542+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T23:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:28:28.631+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T23:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-29T23:30:00+00:00'
[2025-03-30T11:28:28.636+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:28:28.637+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:28:28.639+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:28:28.639+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:28:28.646+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240929T233000, start_date=20250330T112828, end_date=20250330T112828
[2025-03-30T11:28:28.685+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:28:28.730+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:33:07.592+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T23:30:00+00:00 [queued]>
[2025-03-30T11:33:07.608+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T23:30:00+00:00 [queued]>
[2025-03-30T11:33:07.609+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:33:07.623+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-29 23:30:00+00:00
[2025-03-30T11:33:07.626+0000] {standard_task_runner.py:60} INFO - Started process 5513 to run task
[2025-03-30T11:33:07.635+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-29T23:30:00+00:00', '--job-id', '2731', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmp4fnn_fzx']
[2025-03-30T11:33:07.636+0000] {standard_task_runner.py:88} INFO - Job 2731: Subtask create_table
[2025-03-30T11:33:07.650+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:33:07.694+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T23:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:33:07.790+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T23:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-29T23:30:00+00:00'
[2025-03-30T11:33:07.793+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:33:07.794+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:33:07.795+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:33:07.795+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:33:07.806+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240929T233000, start_date=20250330T113307, end_date=20250330T113307
[2025-03-30T11:33:07.851+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:33:07.900+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:38:39.547+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T23:30:00+00:00 [queued]>
[2025-03-30T11:38:39.581+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T23:30:00+00:00 [queued]>
[2025-03-30T11:38:39.582+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:38:39.614+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-29 23:30:00+00:00
[2025-03-30T11:38:39.630+0000] {standard_task_runner.py:60} INFO - Started process 6422 to run task
[2025-03-30T11:38:39.647+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-29T23:30:00+00:00', '--job-id', '3185', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmp9b2nsp0c']
[2025-03-30T11:38:39.651+0000] {standard_task_runner.py:88} INFO - Job 3185: Subtask create_table
[2025-03-30T11:38:39.688+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:38:39.768+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T23:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:38:39.967+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T23:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-29T23:30:00+00:00'
[2025-03-30T11:38:39.977+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:38:39.980+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:38:39.984+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:38:39.985+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:38:40.024+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240929T233000, start_date=20250330T113839, end_date=20250330T113840
[2025-03-30T11:38:40.072+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:38:40.123+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:40:40.353+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T23:30:00+00:00 [queued]>
[2025-03-30T11:40:40.360+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T23:30:00+00:00 [queued]>
[2025-03-30T11:40:40.361+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:40:40.370+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-29 23:30:00+00:00
[2025-03-30T11:40:40.377+0000] {standard_task_runner.py:60} INFO - Started process 6858 to run task
[2025-03-30T11:40:40.383+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-29T23:30:00+00:00', '--job-id', '3404', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpfvmmxvit']
[2025-03-30T11:40:40.386+0000] {standard_task_runner.py:88} INFO - Job 3404: Subtask create_table
[2025-03-30T11:40:40.406+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:40:40.439+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T23:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:40:40.483+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T23:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-29T23:30:00+00:00'
[2025-03-30T11:40:40.489+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:40:40.490+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:40:40.490+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:40:40.490+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:40:40.498+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240929T233000, start_date=20250330T114040, end_date=20250330T114040
[2025-03-30T11:40:40.520+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:40:40.530+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
