[2025-03-30T11:11:56.544+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T17:00:00+00:00 [queued]>
[2025-03-30T11:11:56.566+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T17:00:00+00:00 [queued]>
[2025-03-30T11:11:56.567+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:11:56.589+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-04 17:00:00+00:00
[2025-03-30T11:11:56.606+0000] {standard_task_runner.py:60} INFO - Started process 1194 to run task
[2025-03-30T11:11:56.611+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-04T17:00:00+00:00', '--job-id', '571', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpy4r9b9ad']
[2025-03-30T11:11:56.614+0000] {standard_task_runner.py:88} INFO - Job 571: Subtask create_table
[2025-03-30T11:11:56.644+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:11:56.695+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T17:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:11:56.828+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-04T17:00:00+00:00'
[2025-03-30T11:11:56.835+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:11:56.837+0000] {inout_data.py:124} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:11:56.839+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:11:56.839+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:11:56.854+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241004T170000, start_date=20250330T111156, end_date=20250330T111156
[2025-03-30T11:11:56.915+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:11:56.982+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:18:29.412+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T17:00:00+00:00 [queued]>
[2025-03-30T11:18:29.421+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T17:00:00+00:00 [queued]>
[2025-03-30T11:18:29.421+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:18:29.440+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-04 17:00:00+00:00
[2025-03-30T11:18:29.445+0000] {standard_task_runner.py:60} INFO - Started process 3049 to run task
[2025-03-30T11:18:29.461+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-04T17:00:00+00:00', '--job-id', '1499', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmp2_zh1q74']
[2025-03-30T11:18:29.463+0000] {standard_task_runner.py:88} INFO - Job 1499: Subtask create_table
[2025-03-30T11:18:29.490+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:18:29.543+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T17:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:18:29.657+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-04T17:00:00+00:00'
[2025-03-30T11:18:29.661+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:18:29.664+0000] {inout_data.py:117} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:18:29.665+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:18:29.666+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:18:29.683+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241004T170000, start_date=20250330T111829, end_date=20250330T111829
[2025-03-30T11:18:29.724+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:18:29.761+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:30:46.573+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T17:00:00+00:00 [queued]>
[2025-03-30T11:30:46.579+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T17:00:00+00:00 [queued]>
[2025-03-30T11:30:46.580+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:30:46.587+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-04 17:00:00+00:00
[2025-03-30T11:30:46.591+0000] {standard_task_runner.py:60} INFO - Started process 4970 to run task
[2025-03-30T11:30:46.594+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-04T17:00:00+00:00', '--job-id', '2460', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpx7si_0xn']
[2025-03-30T11:30:46.596+0000] {standard_task_runner.py:88} INFO - Job 2460: Subtask create_table
[2025-03-30T11:30:46.606+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:30:46.637+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-04T17:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:30:46.700+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-04T17:00:00+00:00'
[2025-03-30T11:30:46.703+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:30:46.704+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:30:46.704+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:30:46.705+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:30:46.718+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241004T170000, start_date=20250330T113046, end_date=20250330T113046
[2025-03-30T11:30:46.773+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:30:46.802+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
