[2025-03-30T12:25:10.406+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table manual__2025-03-30T12:25:09.027065+00:00 [queued]>
[2025-03-30T12:25:10.411+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table manual__2025-03-30T12:25:09.027065+00:00 [queued]>
[2025-03-30T12:25:10.411+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T12:25:10.418+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2025-03-30 12:25:09.027065+00:00
[2025-03-30T12:25:10.422+0000] {standard_task_runner.py:60} INFO - Started process 7389 to run task
[2025-03-30T12:25:10.429+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'manual__2025-03-30T12:25:09.027065+00:00', '--job-id', '3670', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmp4k90bvmb']
[2025-03-30T12:25:10.431+0000] {standard_task_runner.py:88} INFO - Job 3670: Subtask create_table
[2025-03-30T12:25:10.439+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T12:25:10.457+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table manual__2025-03-30T12:25:09.027065+00:00 [running]> on host ff9d64b065e6
[2025-03-30T12:25:10.507+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T12:25:09.027065+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-30T12:25:09.027065+00:00'
[2025-03-30T12:25:10.509+0000] {mariadb.py:36} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T12:25:10.509+0000] {inout_data.py:45} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T12:25:10.509+0000] {mariadb.py:72} INFO - MariaDB connection closed.
[2025-03-30T12:25:10.509+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T12:25:10.514+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20250330T122509, start_date=20250330T122510, end_date=20250330T122510
[2025-03-30T12:25:10.526+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T12:25:10.536+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
