[2025-03-30T11:13:26.056+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-07T12:30:00+00:00 [queued]>
[2025-03-30T11:13:26.078+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-07T12:30:00+00:00 [queued]>
[2025-03-30T11:13:26.080+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:13:26.103+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-07 12:30:00+00:00
[2025-03-30T11:13:26.109+0000] {standard_task_runner.py:60} INFO - Started process 1733 to run task
[2025-03-30T11:13:26.114+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-07T12:30:00+00:00', '--job-id', '840', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpvpqnkfwd']
[2025-03-30T11:13:26.116+0000] {standard_task_runner.py:88} INFO - Job 840: Subtask create_table
[2025-03-30T11:13:26.128+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:13:26.157+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-07T12:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:13:26.234+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-07T12:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-07T12:30:00+00:00'
[2025-03-30T11:13:26.239+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:13:26.241+0000] {inout_data.py:124} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:13:26.242+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:13:26.242+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:13:26.252+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241007T123000, start_date=20250330T111326, end_date=20250330T111326
[2025-03-30T11:13:26.295+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:13:26.330+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:20:07.756+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-07T12:30:00+00:00 [queued]>
[2025-03-30T11:20:07.767+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-07T12:30:00+00:00 [queued]>
[2025-03-30T11:20:07.768+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:20:07.788+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-10-07 12:30:00+00:00
[2025-03-30T11:20:07.792+0000] {standard_task_runner.py:60} INFO - Started process 3582 to run task
[2025-03-30T11:20:07.801+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-10-07T12:30:00+00:00', '--job-id', '1765', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmp7__pmymq']
[2025-03-30T11:20:07.804+0000] {standard_task_runner.py:88} INFO - Job 1765: Subtask create_table
[2025-03-30T11:20:07.822+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:20:07.860+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-10-07T12:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:20:07.997+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-07T12:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-07T12:30:00+00:00'
[2025-03-30T11:20:08.011+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:20:08.014+0000] {inout_data.py:117} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:20:08.016+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:20:08.017+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:20:08.037+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20241007T123000, start_date=20250330T112007, end_date=20250330T112008
[2025-03-30T11:20:08.214+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:20:08.510+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
