[2025-03-30T11:10:49.340+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T19:30:00+00:00 [queued]>
[2025-03-30T11:10:49.392+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T19:30:00+00:00 [queued]>
[2025-03-30T11:10:49.399+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:10:49.475+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-10-02 19:30:00+00:00
[2025-03-30T11:10:49.483+0000] {standard_task_runner.py:60} INFO - Started process 839 to run task
[2025-03-30T11:10:49.493+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-10-02T19:30:00+00:00', '--job-id', '394', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpeajas52_']
[2025-03-30T11:10:49.495+0000] {standard_task_runner.py:88} INFO - Job 394: Subtask ingest_dummy_data
[2025-03-30T11:10:49.528+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:10:49.598+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T19:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:10:49.715+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T19:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-02T19:30:00+00:00'
[2025-03-30T11:10:49.729+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:10:49.734+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:49-8808' for key 'PRIMARY'")
[2025-03-30T11:10:49.736+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:49-8808' for key 'PRIMARY'")
[2025-03-30T11:10:49.740+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:49-8808' for key 'PRIMARY'")
[2025-03-30T11:10:49.741+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:49-8808' for key 'PRIMARY'")
[2025-03-30T11:10:49.742+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:49-8808' for key 'PRIMARY'")
[2025-03-30T11:10:49.744+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:49-8808' for key 'PRIMARY'")
[2025-03-30T11:10:49.746+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:49-8808' for key 'PRIMARY'")
[2025-03-30T11:10:49.748+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:49-8808' for key 'PRIMARY'")
[2025-03-30T11:10:49.749+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:49-8808' for key 'PRIMARY'")
[2025-03-30T11:10:49.750+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:49-8808' for key 'PRIMARY'")
[2025-03-30T11:10:49.752+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:10:49-8808' for key 'PRIMARY'")
[2025-03-30T11:10:49.756+0000] {inout_data.py:159} INFO - Ingested 12 rows of dummy data.
[2025-03-30T11:10:49.759+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:10:49.761+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:10:49.779+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20241002T193000, start_date=20250330T111049, end_date=20250330T111049
[2025-03-30T11:10:49.839+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:10:49.876+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:17:25.432+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T19:30:00+00:00 [queued]>
[2025-03-30T11:17:25.438+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T19:30:00+00:00 [queued]>
[2025-03-30T11:17:25.438+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:17:25.447+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-10-02 19:30:00+00:00
[2025-03-30T11:17:25.450+0000] {standard_task_runner.py:60} INFO - Started process 2686 to run task
[2025-03-30T11:17:25.455+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-10-02T19:30:00+00:00', '--job-id', '1318', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmps9ca3pfs']
[2025-03-30T11:17:25.458+0000] {standard_task_runner.py:88} INFO - Job 1318: Subtask ingest_dummy_data
[2025-03-30T11:17:25.469+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:17:25.501+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T19:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:17:25.543+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T19:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-02T19:30:00+00:00'
[2025-03-30T11:17:25.545+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:17:25.546+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:17:25-9403' for key 'PRIMARY'")
[2025-03-30T11:17:25.546+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:17:25-9403' for key 'PRIMARY'")
[2025-03-30T11:17:25.547+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:17:25-9403' for key 'PRIMARY'")
[2025-03-30T11:17:25.547+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:17:25-9403' for key 'PRIMARY'")
[2025-03-30T11:17:25.547+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:17:25-9403' for key 'PRIMARY'")
[2025-03-30T11:17:25.547+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:17:25-9403' for key 'PRIMARY'")
[2025-03-30T11:17:25.548+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:17:25-9403' for key 'PRIMARY'")
[2025-03-30T11:17:25.548+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:17:25-9403' for key 'PRIMARY'")
[2025-03-30T11:17:25.548+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:17:25-9403' for key 'PRIMARY'")
[2025-03-30T11:17:25.548+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:17:25-9403' for key 'PRIMARY'")
[2025-03-30T11:17:25.549+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:17:25-9403' for key 'PRIMARY'")
[2025-03-30T11:17:25.549+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:17:25-9403' for key 'PRIMARY'")
[2025-03-30T11:17:25.549+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:17:25-9403' for key 'PRIMARY'")
[2025-03-30T11:17:25.549+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:17:25-9403' for key 'PRIMARY'")
[2025-03-30T11:17:25.550+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:17:25-9403' for key 'PRIMARY'")
[2025-03-30T11:17:25.550+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:17:25-9403' for key 'PRIMARY'")
[2025-03-30T11:17:25.550+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:17:25-9403' for key 'PRIMARY'")
[2025-03-30T11:17:25.551+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:17:25-9403' for key 'PRIMARY'")
[2025-03-30T11:17:25.551+0000] {inout_data.py:152} INFO - Ingested 19 rows of dummy data.
[2025-03-30T11:17:25.551+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:17:25.551+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:17:25.556+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20241002T193000, start_date=20250330T111725, end_date=20250330T111725
[2025-03-30T11:17:25.598+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:17:25.606+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:29:51.068+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T19:30:00+00:00 [queued]>
[2025-03-30T11:29:51.076+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T19:30:00+00:00 [queued]>
[2025-03-30T11:29:51.076+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:29:51.085+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-10-02 19:30:00+00:00
[2025-03-30T11:29:51.087+0000] {standard_task_runner.py:60} INFO - Started process 4609 to run task
[2025-03-30T11:29:51.089+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-10-02T19:30:00+00:00', '--job-id', '2280', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmps4schblu']
[2025-03-30T11:29:51.091+0000] {standard_task_runner.py:88} INFO - Job 2280: Subtask ingest_dummy_data
[2025-03-30T11:29:51.096+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:29:51.112+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T19:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:29:51.147+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T19:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-02T19:30:00+00:00'
[2025-03-30T11:29:51.148+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:29:51.148+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:29:51.149+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:29:51.149+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:29:51.149+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:29:51.149+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:29:51.149+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:29:51.149+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:29:51.149+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:29:51.150+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:29:51.150+0000] {inout_data.py:87} INFO - Ingested 9 rows of dummy data for 2024-10-02 19:30:00+00:00.
[2025-03-30T11:29:51.150+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:29:51.150+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:29:51.153+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20241002T193000, start_date=20250330T112951, end_date=20250330T112951
[2025-03-30T11:29:51.194+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:29:51.203+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:34:47.722+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T19:30:00+00:00 [queued]>
[2025-03-30T11:34:47.733+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T19:30:00+00:00 [queued]>
[2025-03-30T11:34:47.733+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:34:47.747+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-10-02 19:30:00+00:00
[2025-03-30T11:34:47.752+0000] {standard_task_runner.py:60} INFO - Started process 6065 to run task
[2025-03-30T11:34:47.756+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-10-02T19:30:00+00:00', '--job-id', '3008', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpxi3ppd6z']
[2025-03-30T11:34:47.760+0000] {standard_task_runner.py:88} INFO - Job 3008: Subtask ingest_dummy_data
[2025-03-30T11:34:47.777+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:34:47.810+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-02T19:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:34:48.186+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T19:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-02T19:30:00+00:00'
[2025-03-30T11:34:48.195+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:34:48.196+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 34, 48, 196145), 'timestamp': datetime.datetime(2024, 10, 2, 19, 59, tzinfo=datetime.timezone.utc), 'emp_id': 4517, 'employee_name': 'Employee13', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '2', 'function': 'IT', 'division': 'AAPD', 'department': 'HRSD', 'section': '2'}
[2025-03-30T11:34:48.196+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:34:48.196+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 34, 48, 196933), 'timestamp': datetime.datetime(2024, 10, 2, 19, 46, tzinfo=datetime.timezone.utc), 'emp_id': 6820, 'employee_name': 'Employee94', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '10', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '2'}
[2025-03-30T11:34:48.197+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:34:48.197+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 34, 48, 197465), 'timestamp': datetime.datetime(2024, 10, 2, 19, 49, tzinfo=datetime.timezone.utc), 'emp_id': 3360, 'employee_name': 'Employee14', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '2', 'function': 'IT', 'division': 'AAPD', 'department': 'HRSD', 'section': '2'}
[2025-03-30T11:34:48.197+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:34:48.197+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 34, 48, 197867), 'timestamp': datetime.datetime(2024, 10, 2, 19, 56, tzinfo=datetime.timezone.utc), 'emp_id': 7582, 'employee_name': 'Employee99', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '6', 'function': 'IT', 'division': 'AAPD', 'department': 'ML', 'section': '2'}
[2025-03-30T11:34:48.198+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:34:48.198+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 34, 48, 198420), 'timestamp': datetime.datetime(2024, 10, 2, 19, 38, tzinfo=datetime.timezone.utc), 'emp_id': 4574, 'employee_name': 'Employee22', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '1', 'function': 'IT', 'division': 'AAPD', 'department': 'ML', 'section': '1'}
[2025-03-30T11:34:48.198+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:34:48.198+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 34, 48, 198941), 'timestamp': datetime.datetime(2024, 10, 2, 19, 58, tzinfo=datetime.timezone.utc), 'emp_id': 4246, 'employee_name': 'Employee49', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '7', 'function': 'IT', 'division': 'BSID', 'department': 'HRSD', 'section': '2'}
[2025-03-30T11:34:48.199+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:34:48.199+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 34, 48, 199357), 'timestamp': datetime.datetime(2024, 10, 2, 19, 42, tzinfo=datetime.timezone.utc), 'emp_id': 6160, 'employee_name': 'Employee1', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '2', 'function': 'IT', 'division': 'AAPD', 'department': 'HRSD', 'section': '1'}
[2025-03-30T11:34:48.199+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:34:48.199+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 34, 48, 199692), 'timestamp': datetime.datetime(2024, 10, 2, 19, 44, tzinfo=datetime.timezone.utc), 'emp_id': 5493, 'employee_name': 'Employee86', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '1', 'function': 'IT', 'division': 'AAPD', 'department': 'HRSD', 'section': '2'}
[2025-03-30T11:34:48.199+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:34:48.200+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 34, 48, 200063), 'timestamp': datetime.datetime(2024, 10, 2, 19, 52, tzinfo=datetime.timezone.utc), 'emp_id': 9726, 'employee_name': 'Employee43', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '5', 'function': 'IT', 'division': 'AAPD', 'department': 'HRSD', 'section': '2'}
[2025-03-30T11:34:48.200+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:34:48.200+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 34, 48, 200399), 'timestamp': datetime.datetime(2024, 10, 2, 19, 43, tzinfo=datetime.timezone.utc), 'emp_id': 8710, 'employee_name': 'Employee80', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '4', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '1'}
[2025-03-30T11:34:48.200+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:34:48.200+0000] {inout_data.py:88} INFO - Ingested 10 rows of dummy data for 2024-10-02 19:30:00+00:00.
[2025-03-30T11:34:48.200+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:34:48.201+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:34:48.216+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20241002T193000, start_date=20250330T113447, end_date=20250330T113448
[2025-03-30T11:34:48.287+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:34:48.357+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
