[2025-03-30T11:08:43.837+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T06:00:00+00:00 [queued]>
[2025-03-30T11:08:43.901+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T06:00:00+00:00 [queued]>
[2025-03-30T11:08:43.903+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:08:44.065+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-29 06:00:00+00:00
[2025-03-30T11:08:44.134+0000] {standard_task_runner.py:60} INFO - Started process 132 to run task
[2025-03-30T11:08:44.160+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-29T06:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpb9bj5lox']
[2025-03-30T11:08:44.169+0000] {standard_task_runner.py:88} INFO - Job 37: Subtask create_table
[2025-03-30T11:08:44.209+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:08:44.532+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T06:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:08:45.068+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-29T06:00:00+00:00'
[2025-03-30T11:08:45.081+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:08:45.113+0000] {inout_data.py:124} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:08:45.116+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:08:45.124+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:08:45.181+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240929T060000, start_date=20250330T110843, end_date=20250330T110845
[2025-03-30T11:08:45.350+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:08:45.669+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:15:31.841+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T06:00:00+00:00 [queued]>
[2025-03-30T11:15:31.864+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T06:00:00+00:00 [queued]>
[2025-03-30T11:15:31.864+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:15:31.887+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-29 06:00:00+00:00
[2025-03-30T11:15:31.895+0000] {standard_task_runner.py:60} INFO - Started process 1998 to run task
[2025-03-30T11:15:31.904+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-29T06:00:00+00:00', '--job-id', '973', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpuzwu_qb0']
[2025-03-30T11:15:31.906+0000] {standard_task_runner.py:88} INFO - Job 973: Subtask create_table
[2025-03-30T11:15:31.925+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:15:31.969+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T06:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:15:32.039+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-29T06:00:00+00:00'
[2025-03-30T11:15:32.046+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:15:32.048+0000] {inout_data.py:117} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:15:32.049+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:15:32.049+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:15:32.064+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240929T060000, start_date=20250330T111531, end_date=20250330T111532
[2025-03-30T11:15:32.122+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:15:32.168+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:22:21.873+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T06:00:00+00:00 [queued]>
[2025-03-30T11:22:21.899+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T06:00:00+00:00 [queued]>
[2025-03-30T11:22:21.902+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:22:21.952+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-29 06:00:00+00:00
[2025-03-30T11:22:21.966+0000] {standard_task_runner.py:60} INFO - Started process 3848 to run task
[2025-03-30T11:22:21.977+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-29T06:00:00+00:00', '--job-id', '1898', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpgwg74wj_']
[2025-03-30T11:22:21.985+0000] {standard_task_runner.py:88} INFO - Job 1898: Subtask create_table
[2025-03-30T11:22:22.049+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:22:22.160+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T06:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:22:22.939+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-29T06:00:00+00:00'
[2025-03-30T11:22:22.997+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:22:23.012+0000] {inout_data.py:117} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:22:23.014+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:22:23.020+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:22:23.144+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240929T060000, start_date=20250330T112221, end_date=20250330T112223
[2025-03-30T11:22:23.396+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:22:23.697+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:28:05.088+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T06:00:00+00:00 [queued]>
[2025-03-30T11:28:05.101+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T06:00:00+00:00 [queued]>
[2025-03-30T11:28:05.103+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:28:05.123+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-29 06:00:00+00:00
[2025-03-30T11:28:05.131+0000] {standard_task_runner.py:60} INFO - Started process 3919 to run task
[2025-03-30T11:28:05.147+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-29T06:00:00+00:00', '--job-id', '1934', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmps_jmfwk_']
[2025-03-30T11:28:05.149+0000] {standard_task_runner.py:88} INFO - Job 1934: Subtask create_table
[2025-03-30T11:28:05.169+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:28:05.223+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T06:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:28:05.320+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-29T06:00:00+00:00'
[2025-03-30T11:28:05.328+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:28:05.329+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:28:05.329+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:28:05.330+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:28:05.349+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240929T060000, start_date=20250330T112805, end_date=20250330T112805
[2025-03-30T11:28:05.408+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:28:05.427+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:32:46.210+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T06:00:00+00:00 [queued]>
[2025-03-30T11:32:46.236+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T06:00:00+00:00 [queued]>
[2025-03-30T11:32:46.237+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:32:46.265+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-29 06:00:00+00:00
[2025-03-30T11:32:46.274+0000] {standard_task_runner.py:60} INFO - Started process 5373 to run task
[2025-03-30T11:32:46.289+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-29T06:00:00+00:00', '--job-id', '2661', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpakz_5mca']
[2025-03-30T11:32:46.295+0000] {standard_task_runner.py:88} INFO - Job 2661: Subtask create_table
[2025-03-30T11:32:46.323+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:32:46.389+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T06:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:32:46.529+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-29T06:00:00+00:00'
[2025-03-30T11:32:46.546+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:32:46.548+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:32:46.549+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:32:46.550+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:32:46.560+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240929T060000, start_date=20250330T113246, end_date=20250330T113246
[2025-03-30T11:32:46.590+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:32:46.614+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:35:55.890+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T06:00:00+00:00 [queued]>
[2025-03-30T11:35:55.914+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T06:00:00+00:00 [queued]>
[2025-03-30T11:35:55.915+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:35:55.940+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-29 06:00:00+00:00
[2025-03-30T11:35:55.955+0000] {standard_task_runner.py:60} INFO - Started process 6212 to run task
[2025-03-30T11:35:55.984+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-29T06:00:00+00:00', '--job-id', '3081', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpx7bfv2yc']
[2025-03-30T11:35:55.990+0000] {standard_task_runner.py:88} INFO - Job 3081: Subtask create_table
[2025-03-30T11:35:56.040+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:35:56.123+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T06:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:35:56.257+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-29T06:00:00+00:00'
[2025-03-30T11:35:56.267+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:35:56.269+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:35:56.270+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:35:56.270+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:35:56.288+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240929T060000, start_date=20250330T113555, end_date=20250330T113556
[2025-03-30T11:35:56.313+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:35:56.360+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:38:11.570+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T06:00:00+00:00 [queued]>
[2025-03-30T11:38:11.582+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T06:00:00+00:00 [queued]>
[2025-03-30T11:38:11.584+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:38:11.604+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-29 06:00:00+00:00
[2025-03-30T11:38:11.616+0000] {standard_task_runner.py:60} INFO - Started process 6279 to run task
[2025-03-30T11:38:11.623+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-29T06:00:00+00:00', '--job-id', '3114', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpq_h_zpri']
[2025-03-30T11:38:11.626+0000] {standard_task_runner.py:88} INFO - Job 3114: Subtask create_table
[2025-03-30T11:38:11.685+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:38:11.843+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T06:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:38:12.097+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-29T06:00:00+00:00'
[2025-03-30T11:38:12.123+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:38:12.137+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:38:12.138+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:38:12.139+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:38:12.172+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240929T060000, start_date=20250330T113811, end_date=20250330T113812
[2025-03-30T11:38:12.274+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:38:12.383+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:40:19.614+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T06:00:00+00:00 [queued]>
[2025-03-30T11:40:19.625+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T06:00:00+00:00 [queued]>
[2025-03-30T11:40:19.626+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:40:19.646+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-29 06:00:00+00:00
[2025-03-30T11:40:19.652+0000] {standard_task_runner.py:60} INFO - Started process 6717 to run task
[2025-03-30T11:40:19.659+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-29T06:00:00+00:00', '--job-id', '3333', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpfiffqhy5']
[2025-03-30T11:40:19.661+0000] {standard_task_runner.py:88} INFO - Job 3333: Subtask create_table
[2025-03-30T11:40:19.682+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:40:19.732+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-29T06:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:40:19.829+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-29T06:00:00+00:00'
[2025-03-30T11:40:19.832+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:40:19.833+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:40:19.833+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:40:19.833+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:40:19.845+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240929T060000, start_date=20250330T114019, end_date=20250330T114019
[2025-03-30T11:40:19.924+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:40:19.989+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
