[2025-03-30T11:09:42.920+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T19:00:00+00:00 [queued]>
[2025-03-30T11:09:42.943+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T19:00:00+00:00 [queued]>
[2025-03-30T11:09:42.944+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:09:43.018+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-30 19:00:00+00:00
[2025-03-30T11:09:43.037+0000] {standard_task_runner.py:60} INFO - Started process 441 to run task
[2025-03-30T11:09:43.047+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-30T19:00:00+00:00', '--job-id', '194', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmp4aovf891']
[2025-03-30T11:09:43.048+0000] {standard_task_runner.py:88} INFO - Job 194: Subtask create_table
[2025-03-30T11:09:43.074+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:09:43.183+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T19:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:09:43.327+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T19:00:00+00:00'
[2025-03-30T11:09:43.344+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:09:43.346+0000] {inout_data.py:124} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:09:43.347+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:09:43.348+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:09:43.364+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240930T190000, start_date=20250330T110942, end_date=20250330T110943
[2025-03-30T11:09:43.396+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:09:43.466+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:16:20.267+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T19:00:00+00:00 [queued]>
[2025-03-30T11:16:20.284+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T19:00:00+00:00 [queued]>
[2025-03-30T11:16:20.284+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:16:20.297+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-30 19:00:00+00:00
[2025-03-30T11:16:20.301+0000] {standard_task_runner.py:60} INFO - Started process 2300 to run task
[2025-03-30T11:16:20.304+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-30T19:00:00+00:00', '--job-id', '1124', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpvnkn6v4o']
[2025-03-30T11:16:20.306+0000] {standard_task_runner.py:88} INFO - Job 1124: Subtask create_table
[2025-03-30T11:16:20.325+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:16:20.366+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T19:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:16:20.456+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T19:00:00+00:00'
[2025-03-30T11:16:20.470+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:16:20.472+0000] {inout_data.py:117} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:16:20.473+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:16:20.473+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:16:20.489+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240930T190000, start_date=20250330T111620, end_date=20250330T111620
[2025-03-30T11:16:20.526+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:16:20.578+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:28:55.742+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T19:00:00+00:00 [queued]>
[2025-03-30T11:28:55.758+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T19:00:00+00:00 [queued]>
[2025-03-30T11:28:55.760+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:28:55.795+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-30 19:00:00+00:00
[2025-03-30T11:28:55.801+0000] {standard_task_runner.py:60} INFO - Started process 4217 to run task
[2025-03-30T11:28:55.805+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-30T19:00:00+00:00', '--job-id', '2083', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmp2vjl2kyi']
[2025-03-30T11:28:55.806+0000] {standard_task_runner.py:88} INFO - Job 2083: Subtask create_table
[2025-03-30T11:28:55.832+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:28:55.879+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T19:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:28:56.013+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T19:00:00+00:00'
[2025-03-30T11:28:56.029+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:28:56.034+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:28:56.035+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:28:56.039+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:28:56.060+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240930T190000, start_date=20250330T112855, end_date=20250330T112856
[2025-03-30T11:28:56.113+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:28:56.167+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:33:30.065+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T19:00:00+00:00 [queued]>
[2025-03-30T11:33:30.094+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T19:00:00+00:00 [queued]>
[2025-03-30T11:33:30.095+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:33:30.114+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-30 19:00:00+00:00
[2025-03-30T11:33:30.120+0000] {standard_task_runner.py:60} INFO - Started process 5674 to run task
[2025-03-30T11:33:30.124+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-30T19:00:00+00:00', '--job-id', '2811', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpcn31u78c']
[2025-03-30T11:33:30.126+0000] {standard_task_runner.py:88} INFO - Job 2811: Subtask create_table
[2025-03-30T11:33:30.141+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:33:30.177+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T19:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:33:30.274+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T19:00:00+00:00'
[2025-03-30T11:33:30.279+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:33:30.280+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:33:30.281+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:33:30.282+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:33:30.299+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240930T190000, start_date=20250330T113330, end_date=20250330T113330
[2025-03-30T11:33:30.344+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:33:30.393+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:39:07.984+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T19:00:00+00:00 [queued]>
[2025-03-30T11:39:07.999+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T19:00:00+00:00 [queued]>
[2025-03-30T11:39:08.002+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:39:08.021+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-30 19:00:00+00:00
[2025-03-30T11:39:08.029+0000] {standard_task_runner.py:60} INFO - Started process 6571 to run task
[2025-03-30T11:39:08.032+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-30T19:00:00+00:00', '--job-id', '3260', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpzl02sbzj']
[2025-03-30T11:39:08.034+0000] {standard_task_runner.py:88} INFO - Job 3260: Subtask create_table
[2025-03-30T11:39:08.052+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:39:08.084+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T19:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:39:08.175+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T19:00:00+00:00'
[2025-03-30T11:39:08.185+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:39:08.187+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:39:08.188+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:39:08.191+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:39:08.203+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240930T190000, start_date=20250330T113907, end_date=20250330T113908
[2025-03-30T11:39:08.258+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:39:08.289+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:41:12.447+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T19:00:00+00:00 [queued]>
[2025-03-30T11:41:12.473+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T19:00:00+00:00 [queued]>
[2025-03-30T11:41:12.474+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:41:12.508+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_table> on 2024-09-30 19:00:00+00:00
[2025-03-30T11:41:12.515+0000] {standard_task_runner.py:60} INFO - Started process 7008 to run task
[2025-03-30T11:41:12.533+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'create_table', 'scheduled__2024-09-30T19:00:00+00:00', '--job-id', '3479', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmph6tsf9zu']
[2025-03-30T11:41:12.536+0000] {standard_task_runner.py:88} INFO - Job 3479: Subtask create_table
[2025-03-30T11:41:12.565+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:41:12.669+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.create_table scheduled__2024-09-30T19:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:41:12.841+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T19:00:00+00:00'
[2025-03-30T11:41:12.855+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:41:12.857+0000] {inout_data.py:46} INFO - Table emp_inout_rec created (if it didn't exist).
[2025-03-30T11:41:12.858+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:41:12.861+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:41:12.880+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=create_table, execution_date=20240930T190000, start_date=20250330T114112, end_date=20250330T114112
[2025-03-30T11:41:12.959+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:41:13.047+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
